### ISSUE TITLE
Bartender 无法隐藏这个app

### ISSUE THREAD

**Issue by jsmjsm** [leaves615/KeyboardHolder#1]
Bartender 无法隐藏这个app，试了好几次都隐藏失败

**Comment by leaves615** [comment]
没搞明白 Bartender 科技是这么隐藏的。
app（self）没有进行任何阻碍。

**Comment by paullbyao** [comment]
这边MacOS 10.15.1 + Bartender 3.1.7 环境使用正常，可以隐藏
