### ISSUE TITLE
version 1.3.1 missing in "update.xml"

### ISSUE THREAD

**Issue by core-code** [leaves615/KeyboardHolder#10]
auto update to new version impossible

**Comment by leaves615** [comment]
Is it a network problem?
My update check is working fine.

**Comment by core-code** [comment]
ah ok the feed has changed

https://raw.githubusercontent.com/leaves615/KeyboardHolder/master/update.xml
=>
https://keyboardholder.leavesc.com/distribute/update.xml

all good now, thanks
