### ISSUE TITLE
bug in vscode terminal

### ISSUE THREAD

**Issue by Macrohoo** [leaves615/KeyboardHolder#100]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/15125523/211823943-724a04c4-8d30-49f4-8bf7-8b08965129dd.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/15125523/211823980-ca191cdd-3c00-467c-a28b-20e71249718e.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/15125523/211824118-3b8ed4f5-8577-48e9-928f-dd682e3019f1.png">

**Comment by leaves615** [comment]
麻烦参照 #56  描述问题。谢谢。
