### ISSUE TITLE
1.1.0.4版本在一个应用的输入过程中会自动切换回英文输入法

### ISSUE THREAD

**Issue by ohnewguy** [leaves615/KeyboardHolder#102]
今天早上在升级了1.1.0.4版本以后，无论是在chrome，还是在powerpoint在输入的中文输入的过程中输入法会自动切换会英文输入法，发生的时间随机，关闭holder以后问题消失。 我的操作系统版本是macOS 13.1

**Comment by hqyxd** [comment]
我的情况和你的刚好相反 设置状态是英文 一开始在应用里面确实是英文 过一会就变成中文了 也是随机时间

**Comment by leaves615** [comment]
请参照 #56 提供相关信息。谢谢。

**Comment by ohnewguy** [comment]
问题描述: 如1st thread
应用版本  1.10.4
操作系统版本 13.1
问题可复现的操作步骤: 打开已经在custom中设置的应用(打开时百度输入法，激活时上一次输入法，开始中文输入，随机时间会切换到英文输入法)
问题时段和日志文件: 9:23, [9:26,9:27,9:28]([url](url))
[cn.leaves.KeyboardHolder 2023-02-17--01-27-57-297.log](https://github.com/leaves615/KeyboardHolder/files/10762399/cn.leaves.KeyboardHolder.2023-02-17--01-27-57-297.log)
[cn.leaves.KeyboardHolder 2023-02-16--11-55-22-903.log](https://github.com/leaves615/KeyboardHolder/files/10762401/cn.leaves.KeyboardHolder.2023-02-16--11-55-22-903.log)
是否启用了辅助控制: 否

**Comment by leaves615** [comment]
2023/02/17 01:27:06:844  app Optional("ThunderHelper") launched. pid: 14072
2023/02/17 01:27:06:844  switch input for app com.xunlei.Thunder.ThunderHelper

迅雷的[ThunderHelper]这个程序影响到了。

可以尝试找到它，并添加到应用排除清单。

**Comment by ohnewguy** [comment]
我在starup items里面找到了这个进程，但是他并不是某一个单独的程序，而是迅雷.app的库中包含的文件，应该是迅雷程序后台守护进程，我尝试把迅雷.app加到了app exlude里面，但是没有用

**Comment by ohnewguy** [comment]
暂时使用tecent lemon，在startup items里面禁用thunderhelper似乎解决了现在的问题，迅雷打开也不影响，还需要再验证一下。

**Comment by hqyxd** [comment]
问题描述: 如1st thread
应用版本 1.10.4
操作系统版本 12.5
问题可复现的操作步骤: 终端设置输入法是英文 一开始在终端里面确实是英文 过一会就变成中文了 也是随机时间 其他设置英文的app里面操作也是一样的结果
问题时段和日志文件:11:35 11:43 cn.leaves.KeyboardHolder 2023-02-16--08-04-29-307.log 
是否启用了辅助控制: 否

**Comment by hqyxd** [comment]
[cn.leaves.KeyboardHolder 2023-02-16--08-04-29-307.log](https://github.com/leaves615/KeyboardHolder/files/10762981/cn.leaves.KeyboardHolder.2023-02-16--08-04-29-307.log)
日志文件在这里

**Comment by leaves615** [comment]
@hqyxd 你的情况跟 @hqyxd 类似，不过是 com.apple.DiagnosticsReporter 这个程序导致的。 
下个版本优化下，对类似情况的探测能力。 感谢反馈。

**Comment by leaves615** [comment]
> @hqyxd 你的情况跟 @hqyxd 类似，不过是 com.apple.DiagnosticsReporter 这个程序导致的。 下个版本优化下，对类似情况的探测能力。 感谢反馈。

这个问题是你的某个程序频繁奔溃，引发的连锁反应。

**Comment by hqyxd** [comment]
> > @hqyxd 你的情况跟 @hqyxd 类似，不过是 com.apple.DiagnosticsReporter 这个程序导致的。 下个版本优化下，对类似情况的探测能力。 感谢反馈。
> 
> 这个问题是你的某个程序频繁奔溃，引发的连锁反应。

啥意思？ 是什么原因？

**Comment by hqyxd** [comment]
@leaves615  我这个问题应该怎么弄？

**Comment by hqyxd** [comment]
问题描述: 回退版本就没有出现问题
应用版本 1.10.3
操作系统版本 12.5
问题可复现的操作步骤: 终端设置输入法是英文 一开始在终端里面确实是英文 过一会就变成中文了 也是随机时间 其他设置英文的app里面操作也是一样的结果
问题时段和日志文件:17:06 17:06
[cn.leaves.KeyboardHolder 2023-02-17--09-06-33-589.log](https://github.com/leaves615/KeyboardHolder/files/10765086/cn.leaves.KeyboardHolder.2023-02-17--09-06-33-589.log)

是否启用了辅助控制: 否

**Comment by hqyxd** [comment]
@leaves615  我把版本回退之后就没有问题了 可以看看日志是咋回事

**Comment by ohnewguy** [comment]
我也觉得不仅仅是冲突的问题，之前我也安装了迅雷，holder就没有发现这个问题

**Comment by leaves615** [comment]
日志体现出来的是  com.apple.DiagnosticsReporter 和 com.xunlei.Thunder.ThunderHelper 在频繁启动和终止。 
当然app没能很好地处理这些干扰。

**Comment by leaves615** [comment]
更新了新版，辛苦验证下是否还有类似问题。

**Comment by ohnewguy** [comment]
之前的1.10.5的版本已经不会出现上述问题，现在1.10.6也没有出现
