### ISSUE TITLE
1.10.4 版本Alfred设置了自动切换输入法不生效

### ISSUE THREAD

**Issue by iRubbish** [leaves615/KeyboardHolder#104]
Alfred设置了自动切换输入法不生效
1.10.4
13.2
添加应用设置输入法规则，打开Alfred应用不管是搜索还是进入应用界面都未生效
日志路径未找到 KeyboardHolder
启用了辅助控制，企微跟iterm2 正常

经测试还未修复，大佬我找不到你的问题反馈中的日志文件。不知道是不是我的电脑设置问题还是？求解

**Comment by leaves615** [comment]
我本机测试是没有问题呀。

**Comment by leaves615** [comment]
提供下日志。

**Comment by iRubbish** [comment]
怎么提供日志，日志文件没找到呢

**Comment by leaves615** [comment]
#56

**Comment by iRubbish** [comment]
更新到你的最新版本测试解决啦大佬，感谢感谢
痛点解决了，建议大佬添加批量添加软件。现在每次添加app只能一个一个添加

**Comment by iRubbish** [comment]
还有一个问题

**Comment by iRubbish** [comment]
在使用中我发现切换的时候，有时候会卡彩虹圈🌈
而且我没整明白
激活的上一次使用的输入的逻辑是啥，例如
iterm2 设置启动英文，激活是上一次使用输入法
通用配置 启动简体中文，激活简体中文

我这样配置后，我点企业微信都是能正常切中文的
然后进到iterm2的时候并没有正常切到英文，然后我手动切英文。再次切到企业微信自动切中文，回到iterm2的时候还是中文并没有自动切。我的理解 激活的 上次使用输入法是我在iterm2时切换英文的话，那么我切到别的软件输入法中文，回到iterm2时也会回到英文。
经常卡彩虹圈 ，求修复。影响使用了！

**Comment by iRubbish** [comment]
日志文件太大我传到了奶牛上了，

链接：https://cowtransfer.com/s/a55adfbb769940 
口令：gxsxvj

大佬，请接收

**Comment by leaves615** [comment]
从日志上看你配置的启动输入法和激活输入法都是拼音输入法。 再者未看到你配置iterm2 的自定义配置。
如果你期望启动时候自动切换拼音，就配置启动输入法为拼音。 激活（窗口切换）是保持上次使用的输入法，配置激活输入法未为上次使用的输入法。

自定义配置是但希望某些app切换规则与默认配置不一样的时候才配置。 大部分应用使用默认配置就可以了。没必要每个应用都进行相同的自定义配置。

**Comment by leaves615** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/375323/220385882-c15b5a8d-1b31-4b78-b260-7dfda2aebc21.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/375323/220385928-d02d9b0c-46ec-4a9e-baa9-9dca8f736ad1.png">
可以看看我的配置。

**Comment by iRubbish** [comment]
好的大佬，感谢分享你的配置
我现在就常用的设置英文输入法，其他都为默认配置启动中文，激活 上次使用的输入法。
现在在使用过程中经常卡彩虹圈，根据我的日志 能看出是bug不还是就我电脑问题？
