### ISSUE TITLE
飞书兼容问题

### ISSUE THREAD

**Issue by 0987363** [leaves615/KeyboardHolder#107]
问题描述：微信、飞书都设置为搜狗，启动和激活都是搜狗，其他应用默认abc。
                      微信和finder之间切换正常。
                      飞书和finder之间来回切换的时候，飞书被设置为了abc。
                     不是一直出现，用一段时间就会出现这问题

    飞书版本： v5.32.6，官网下载，不是mas版本
    应用版本: v1.10.6
    操作系统版本: 13.2.1 (m1)

**Comment by leaves615** [comment]
#56 参照问题反馈提供相关内容。谢谢。
