### ISSUE TITLE
内存使用量过高

### ISSUE THREAD

**Issue by leaf-hsiao** [leaves615/KeyboardHolder#110]
在系统升级到13.3后频繁出现
![7691680225031_ pic](https://user-images.githubusercontent.com/9102854/228999633-3c8a0d95-0b87-4f47-8abd-426e758f5ede.jpg)

**Comment by leaves615** [comment]
你用了几天，达到这个量级呢？

**Comment by leaf-hsiao** [comment]
大约2天左右，kill 后重新启动，没再出现过高的现象。

**Comment by leaf-hsiao** [comment]
升级13.3.1后又出现该情况了，系统升级完重启大约半天左右
<img width="638" alt="image" src="https://user-images.githubusercontent.com/9102854/230835504-3f4507d2-b810-477c-bee4-9ca505c938f5.png">

**Comment by leaves615** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/375323/230839460-38ca5929-c8c7-4681-a071-8e29a423eaa7.png">
和你系统一样。我这边内存占用，还是正常的。

重新启动app再看看。

**Comment by chenshanb3** [comment]
你不会所有程序都设置输入法了吧？是不是设置太多，不停的切换程序导致的？

**Comment by leaves615** [comment]
应该是某个app不兼容导致的，具体是什么，没法静态分析。

**Comment by leaf-hsiao** [comment]
设置了三个，我尝试排除一下

**Comment by leaves615** [comment]
> 我最近一周也经常发生这个情况，经常占用16G左右，然后unresponsive问要不要force quit

有影响就 force quit下，重启。

你们常用什么浏览器？

**Comment by leaf-hsiao** [comment]
> > 我最近一周也经常发生这个情况，经常占用16G左右，然后unresponsive问要不要force quit
> 
> 有影响就 force quit下，重启。
> 
> 你们常用什么浏览器？

Firefox，我的应该是 Citrix Workspace  不兼容导致，移除了就正常了，看是否能兼容一下

**Comment by leaves615** [comment]
> > > 我最近一周也经常发生这个情况，经常占用16G左右，然后unresponsive问要不要force quit
> > 
> > 
> > 有影响就 force quit下，重启。
> > 你们常用什么浏览器？
> 
> Chrome，谢谢大佬🥹

同样是 Chrome，我没有发现高内存的问题。 看看是不是其他 app 引发的。

**Comment by leaves615** [comment]
> > > > 我最近一周也经常发生这个情况，经常占用16G左右，然后unresponsive问要不要force quit
> > > 
> > > 
> > > 有影响就 force quit下，重启。
> > > 你们常用什么浏览器？
> > 
> > 
> > Chrome，谢谢大佬🥹
> 
> 同样是 Chrome，我没有发现高内存的问题。 看看是不是其他 app 引发的。

我装一个试试去。使用频繁吗？

**Comment by leaves615** [comment]
新版本优化了内存占用问题。

**Comment by leaf-hsiao** [comment]
> 新版本优化了内存占用问题。

目前用下来没再出现问题了～感谢
