### ISSUE TITLE
无法设置开机启动

### ISSUE THREAD

**Issue by teal024** [leaves615/KeyboardHolder#112]
系统：Mac OS ventura 13.3.1
描述：在软件内设置开机启动无效，将软件添加进系统偏好设置中的login items登录项没有反应

**Comment by leaves615** [comment]
开启软件自带的开机启动

**Comment by teal024** [comment]
就是软件自带的开机启动选项无效

**Comment by chenshanb3** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/96278502/233831937-9603b2ea-7167-4869-bc1c-d90290930949.png">

在这里加可以实现自动启动吗？@teal024

**Comment by teal024** [comment]
就是添加进登录项(login items)没有反应；现在降级了系统已经能够自启；感谢您的回复
<img width="476" alt="image" src="https://user-images.githubusercontent.com/94586647/233834380-879049b3-4882-47be-8b92-9ca3ad48ae4e.png">
