### ISSUE TITLE
CPU持续占用过高

### ISSUE THREAD

**Issue by huangyxi** [leaves615/KeyboardHolder#116]
1. 在电脑静息状态下占用CPU持续过高（M2 max下接近600%），最近才出现的问题，不知道是否跟新系统有关
2. 应用版本 1.11.0
3. macOS 13.3.1
4. 暂无复现步骤，不知道能否从日志中发现
5. 应用日志 + 活动监视器日志
[cn.leaves.KeyboardHolder 2023-05-13--07-15-33-852.log](https://github.com/leaves615/KeyboardHolder/files/11469781/cn.leaves.KeyboardHolder.2023-05-13--07-15-33-852.log)
[Sample of KeyboardHolder.txt](https://github.com/leaves615/KeyboardHolder/files/11469786/Sample.of.KeyboardHolder.txt)
6. 辅助功能是否启用：是

**Comment by leaves615** [comment]
新版本优化了内存占用问题。

**Comment by huangyxi** [comment]
截止目前，新版本暂未出现上述问题，感谢作者
