### ISSUE TITLE
如何备份配置

### ISSUE THREAD

**Issue by selierlin** [leaves615/KeyboardHolder#119]
有的时候配置的多了，所有有这个需求同步到另外一台设备，请问是否可以实现

**Comment by leaves615** [comment]
你可以尝试复制 `/Users/<username>/Library/Preferences/cn.leaves.KeyboardHolder.plist` 文件到另外一台设备。
> 覆盖文件时，先退出app。

**Comment by selierlin** [comment]
好的，谢谢
