### ISSUE TITLE
请教大佬几个问题

### ISSUE THREAD

**Issue by bosconb** [leaves615/KeyboardHolder#12]
big sur 11.2.3
KeyboardHolder 1.3.1

1、我看到主要功能里有一项是“悬浮窗口支持”，但在我安装的1.3.1 版本中并没有看到有悬浮窗口的选项，只有菜单栏有个程序图标显示。
2、已开启辅助功能
![image](https://user-images.githubusercontent.com/47100031/115948072-75cdc480-a4fe-11eb-8e47-d2acbcff52c6.png)
但是当前运行的程序还是只能看到极个别程序，能否支持像[自动切换输入法](https://www.better365.cn/AutoSwitchInput.html)一样即开即点？
![image](https://user-images.githubusercontent.com/47100031/115948098-9564ed00-a4fe-11eb-8856-38956c19a756.png)

3、有没有计划在此后的版本新增输入状态提示功能，我试过hammerspoon脚本提示，不太理想，目前是用[showyedge](https://showyedge.pqrs.org/)提示当前的输入法状态

4、添加path finder后，名称栏是空白的
![image](https://user-images.githubusercontent.com/47100031/115948613-b549e000-a501-11eb-909c-af242392bf6c.png)

**Comment by leaves615** [comment]
1.  悬浮窗口的设置跟普通窗口的设置是一致的。比如alfred、spotlight。
2. 这个建议会认真考虑。
3. 后续有计划加入输入法切换提示。
4. 请问这个app 名称是什么？我测试一下名称为什么没有正确获取。

**Comment by bosconb** [comment]
> 1.悬浮窗口的设置跟普通窗口的设置是一致的。比如alfred、spotlight。
是说这个设置窗口吗?那可能是我理解错了，我以为是类似输入状态的提示小窗
![image](https://user-images.githubusercontent.com/47100031/115950538-6787a480-a50e-11eb-9215-ad5180bedf93.png)

> 2. 这个建议会认真考虑。
> 3. 后续有计划加入输入法切换提示。

期待更多的功能！

> 4. 请问这个app 名称是什么？我测试一下名称为什么没有正确获取。

[Path Finder 10.0.4](https://cocoatech.com/)
