### ISSUE TITLE
提个建议, 可以识别微信输入法的英文中文状态吗

### ISSUE THREAD

**Issue by each1024T** [leaves615/KeyboardHolder#123]
我看到有些软件是可以识别搜狗输入法的英文中文状态的

---

实现使用一个输入法也能够正确切换, 因为我发现 mac 再打字是, 切换输入法会不生效. 只有停下来才生效

---

[这是 v2 链接](https://www.v2ex.com/t/962013#reply18)

**Comment by leaves615** [comment]
v2 的post 没看到哪个软件可以识别第三方输入法的中英文状态。 你说的是哪个呢？
