### ISSUE TITLE
从通知中心激活应用无法切换输入法

### ISSUE THREAD

**Issue by rrriiicccooo** [leaves615/KeyboardHolder#124]
应用版本：1.12.1
比如主要窗口在Safari，此时输入法为英文，通过点击通知banner进入微信/信息APP，输入法依旧保持英文没能成功切换为中文

**Comment by Sean0717** [comment]
这次的1.12版是负优化切换逻辑,我都换回1.10版本了, 你切换一下应用,它会跟着该应用的输入法而改变,而不是记住切换前的输入法,可能是UI改了,逻辑有点混乱了

**Comment by leaves615** [comment]
> 应用版本：1.12.1 比如主要窗口在Safari，此时输入法为英文，通过点击通知banner进入微信/信息APP，输入法依旧保持英文没能成功切换为中文

基本测试没发现问题，请参照 #56  提供详情信息，进一步分析问题。

**Comment by leaves615** [comment]
> 这次的1.12版是负优化切换逻辑,我都换回1.10版本了, 你切换一下应用,它会跟着该应用的输入法而改变,而不是记住切换前的输入法,可能是UI改了,逻辑有点混乱了

基本测试没发现问题，请参照 #56  提供详情信息，进一步分析问题。

**Comment by leaves615** [comment]
未提交更多信息用于分析问题，改issues暂时关闭。更多功能关注新版本发布。
