### ISSUE TITLE
macos 13.4.1 设置快捷键后无法切换hallelujahIM输入法

### ISSUE THREAD

**Issue by macOSWk** [leaves615/KeyboardHolder#126]
如上
<img width="795" alt="截屏2023-08-21 上午9 29 06" src="https://github.com/leaves615/KeyboardHolder/assets/86730293/6b696d86-debd-4f5c-9fbb-31c5e9aa5d72">

**Comment by macOSWk** [comment]
https://github.com/dongyuwei/hallelujahIM

**Comment by leaves615** [comment]
输入法切换快捷键采用全局快捷键配置，如果配置的快捷键与其他软件冲突了，则有可能不生效。 请还一个试试。

**Comment by macOSWk** [comment]
行关机完快捷键可以用了
