### ISSUE TITLE
[功能建议]在不同app中可以自动切换中英文

### ISSUE THREAD

**Issue by wallleap** [leaves615/KeyboardHolder#13]
希望可以实现这样的功能：
- 默认是搜狗输入法
- 在某些app中(例如PS)，可以自动切换为英文
- 在浏览器输入链接的地方可以自动切换为英文
- 在其他未设置的地方默认是搜狗中文

最后，感谢开发者无私奉献

**Comment by leaves615** [comment]
> 希望可以实现这样的功能：
> 
> * 默认是搜狗输入法
> * 在某些app中(例如PS)，可以自动切换为英文

> * 在其他未设置的地方默认是搜狗中文
> 
> 最后，感谢开发者无私奉献

上述部分功能，已经可以支持的。
![image](https://user-images.githubusercontent.com/375323/118450206-856bb200-b726-11eb-8945-5017f8b2782d.png)
1. 1号位置为默认输入法配置。所有未进行自定义配置的app都采用末日输入法配置规则。
2. 2好位置可以自定义配置app的输入法。

> * 在浏览器输入链接的地方可以自动切换为英文
该功能提议可考虑加入。

**Comment by wallleap** [comment]
好的呢，谢谢大佬
