### ISSUE TITLE
KeyboardHolder 无法打开

### ISSUE THREAD

**Issue by Songggggr** [leaves615/KeyboardHolder#130]
更新到 v1.12.2 后，每次重启系统都会报错
![image](https://github.com/leaves615/KeyboardHolder/assets/131334123/dc49427b-f707-4d39-aae0-dc2af59e40af)

**Comment by haokejie** [comment]
我也遇到一个同样的错误，同样也是本次更新后出现，系统版本 13.5.1  处理器 intel

**Comment by leaves615** [comment]
#131

**Comment by leaves615** [comment]
v1.12.3 已修复
