### ISSUE TITLE
mac  允许在后台

### ISSUE THREAD

**Issue by zhangninghai** [leaves615/KeyboardHolder#133]
被这软件整疯了，软件删除了  允许在后台图标还在，删都删不掉 醉了
<img width="488" alt="截屏2023-09-27 13 16 43" src="https://github.com/leaves615/KeyboardHolder/assets/45140534/650cec9f-4612-418a-96f9-5b8b7b483b6c">

**Comment by leaves615** [comment]
热心大佬已在tg群提供解决方案了。

**Comment by KangodYan** [comment]
怎么解决的，能贴个链接或截图吗

**Comment by KangodYan** [comment]
有空记得提供一下解决方法，谢谢。其他人遇到这个估计还会来问的

**Comment by zhangninghai** [comment]
太久了忘记怎么解决了，强迫症先重装系统吧，没用着软件了

**Comment by zhangninghai** [comment]
> 有空记得提供一下解决方法，谢谢。其他人遇到这个估计还会来问的


太久了忘记怎么解决了，强迫症先重装系统吧，没用着软件了

**Comment by leaves615** [comment]
<img width="734" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/375323/320adb66-3e56-497f-9824-0a789b16addb">

**Comment by KangodYan** [comment]
这个目录下没有，我很久之前就找过了。我又用`KeyboardHolder`名字全局搜索了一下，CPU 直接100度狂干10分钟，也没搜到其他的，有两个感觉都是不相关的。

不行就算了，反正我也快习惯了...

![image](https://github.com/leaves615/KeyboardHolder/assets/36319737/9650f054-fe8b-423e-8037-4f31bdfb42af)

**Comment by leaves615** [comment]
<img width="683" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/375323/4f98fc43-9e17-4f41-a5d1-f426abe412d1">
你搜索不到，有可能是你系统的 launchd 的缓存问题了。
