### ISSUE TITLE
mac 14 之后切换会有一个自带的图标

### ISSUE THREAD

**Issue by each1026** [leaves615/KeyboardHolder#134]
![Image 2023-10-17 at 14 17 03@2x](https://github.com/leaves615/KeyboardHolder/assets/43348055/188a11d6-9c86-457c-93a2-5e0f196681b0)

这个图标要怎么去除啊, 跟我们功能重叠了

**Comment by leaves615** [comment]
系统自带的功能，我没找到关闭开关。 macOS 14 系统可以关闭app的提示用系统自带的。我就是这么配置。
