### ISSUE TITLE
启动项KeyboardHolder删不掉也找不到是怎么回事？

### ISSUE THREAD

**Issue by Aukifei** [leaves615/KeyboardHolder#137]
能查到对应的启动项是cn.leaves.KeyboardHolderLaunchHelper，但是删不掉

**Comment by leaves615** [comment]
可以通过配置窗口，关闭开机启动。

**Comment by Aukifei** [comment]
> 可以通过配置窗口，关闭启动启动。

不行，完全改不了，最后重置BTM才删掉的
