### ISSUE TITLE
希望可以更新一个功能！在每次选中输入框的时候，调用Sonoma切换输入法的pop-up【见下图】

### ISSUE THREAD

**Issue by EthanPixar** [leaves615/KeyboardHolder#139]
<img width="89" alt="Screenshot 2023-11-19 at 22 50 37" src="https://github.com/leaves615/KeyboardHolder/assets/120730787/6c875622-dc82-44d3-ac02-04e0d3f12ec5">

作为一个大学生，很多时候输入的语言并不是和application绑定的，如果能在输入之前就提示一下，这样我就能知道自己用的输入法对不对了，以便于及时切换，如果要看 menu bar 里的输入法信息，每次打字都要多一步操作，十分打断那些文思泉涌的时刻，

希望能调用文本框输入之前就自动提示，不知道是否您能做到，非常感谢您的软件！！

**Comment by leaves615** [comment]
输入法提示可以实现这个功能。

你图示的提示是Sonoma 系统自带的。目前第三方app无法调用的。

**Comment by EthanPixar** [comment]
我明白！但是可不可以换个方法，比如输入前先自动点两下caplocks，就可以调用出来了！！

**Comment by EthanPixar** [comment]
输入法提示不是很稳定，而且位置也不如这个好

**Comment by leaves615** [comment]
暂时不考虑变更现有功能。

**Comment by EthanPixar** [comment]
明白了，现在的功能已经做够好用了，十分感谢！！
