### ISSUE TITLE
【功能建议】切换应用显示当前输入法、快捷键显示当前输入法等功能

### ISSUE THREAD

**Issue by HaoshuaiXu** [leaves615/KeyboardHolder#14]
类似于 [Input Source Pro](https://apps.apple.com/cn/app/input-source-pro/id1537056428?mt=12) 和 [isHUD](https://apps.apple.com/cn/app/ishud/id484757536?mt=12) 的功能

**Comment by leaves615** [comment]
最新版本已支持。
