### ISSUE TITLE
输入法快捷键失效

### ISSUE THREAD

**Issue by xuexuguang** [leaves615/KeyboardHolder#140]
为了更精准分析您遇到的问题。在填写时候请提供一下信息：

问题描述：输入搜狗输入法快捷键之后，无法生效
<img width="836" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/22195079/a0882bc2-2df0-42a6-b15b-3be6085cea27">

应用版本：1.12.7
操作系统版本：MacOs 14.2.1 (23C71)
问题可复现的操作步骤

1、设置vscode输入法
<img width="836" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/22195079/c744c30e-fb34-46a0-a4bd-1748647c9345">

2、打开vscode编辑器，切换为英文 

3、输入快捷键，期望切换会搜狗输入法中文，没办法生效 

问题时段和日志文件（可在 /Users/<username>/Library/Logs/KeyboardHolder 中找到【v1.10.6及以后版本可通过菜单栏图标快捷打开日志所在文件夹】）
<img width="1827" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/22195079/b06dfa8b-5f10-4aa2-9bfd-77abbb4ded0d">

是否启用了辅助控制：已启用

<img width="751" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/22195079/93006861-e1b3-4a0e-bcc9-4c151761f6a3">

**Comment by leaves615** [comment]
只是vscode 中快捷键无效的话，就是你设置的快捷键与vscode的快捷键有冲突。

xiaoyi ***@***.***> 于2023年12月26日周二 12:19写道：
