### ISSUE TITLE
菜单栏隐藏后就怎么也打不开面板了

### ISSUE THREAD

**Issue by CuteWans** [leaves615/KeyboardHolder#142]
试过了快捷键没用，删除`cn.leaves.KeyboardHolder.plist`配置文件后重启没用，删除所有搜得到的相关内容重装也没用`find ~ -iname '*keyboardholder*' -exec rm -rf -- '{}' \;`，到底该咋整啊，是macos的bug吗

**Comment by CuteWans** [comment]
macos：ventura 13.4 应用版本：1.12.8

**Comment by leaves615** [comment]
在确定KeyboardHolder 已启动情况下，再次通过图标启动app，状态栏图标回再次显示。

**Comment by CuteWans** [comment]
> 在确定KeyboardHolder 已启动情况下，再次通过图标启动app，状态栏图标回再次显示。

之后点击图标启动都没有任何反应了，没有ui界面也没有状态栏图标

**Comment by platelett** [comment]
> 试过了快捷键没用，删除`cn.leaves.KeyboardHolder.plist`配置文件后重启没用，删除所有搜得到的相关内容重装也没用`find ~ -iname '*keyboardholder*' -exec rm -rf -- '{}' \;`，到底该咋整啊，是macos的bug吗

@CuteWans  同样的问题，删除 ~ 下所有 keyboardholder + 重装解决不了。

**Comment by leaves615** [comment]
确认你有没有用状态栏相关工具，隐藏了图标。

**Comment by platelett** [comment]
@leaves615 感谢！重启之后确实有状态栏图标
