### ISSUE TITLE
电脑重启或者开机后会打开终端窗口

### ISSUE THREAD

**Issue by coo0** [leaves615/KeyboardHolder#144]
运行命令 /Applications/KeyboardHolder.app/Contents/MacOS/KeyboardHolder ; exit
辅助功能已经添加权限
macos 系统版本：12.7.3

**Comment by ybdt** [comment]
同样问题 +1

**Comment by leaves615** [comment]
为什么不是 双击KeyboardHolder.app 打开程序呢？

**Comment by ybdt** [comment]
每次开机都双击启动感觉麻烦（虽然我也是很久才重启一次），就勾选了开机自启

**Comment by leaves615** [comment]
最新版本修复了app自带的开机启动功能，可以正常使用。 如不正常可通过 系统设置-通用-登录项 添加app 到登录时打开清单实现开机启动。

> 通过binary文件启动程序可能会出现未知情况。建议通过bundle方式启动（通过Finder/启动台打开app）。

**Comment by Jonnyan404** [comment]
> 最新版本修复了app自带的开机启动功能，可以正常使用。 如不正常可通过 系统设置-通用-登录项 添加app 到登录时打开清单实现开机启动。
> 
> > 通过binary文件启动程序可能会出现未知情况。建议通过bundle方式启动（通过Finder/启动台打开app）。

从1.12.7之后的版本,每次开机自启都弹出个命令行窗口,窗口还不能自动关闭,只要手动关闭就会导致应用退出......
能整个关闭更新提示么?  退回1.12.7不更新了
