### ISSUE TITLE
自定义设置需要设置启动、激活，能否结合具体的使用场景来说明一下二者的区别？

### ISSUE THREAD

**Issue by Xiaoqing2265** [leaves615/KeyboardHolder#145]
自定义设置需要设置启动、激活，能否结合具体的使用场景来说明一下二者的区别？

**Comment by Xiaoqing2265** [comment]
感恩您的讲解，根据你的描述你对启动以及激活与我的理解是一致，但是作者为什么分成激活、启动要解决的痛点问题并不是很了解？

**Comment by leaves615** [comment]
app激活阶段可配置固定输入法和上次使用的输入法两种。

**Comment by fuyao123** [comment]
为什么mac os14.4开机启动不好使？希望有统计一共切换多少次显示

**Comment by vickllny** [comment]
> 为什么mac os14.4开机启动不好使？希望有统计一共切换多少次显示

同问。我的是14.3，开机启动不会自启动，我确定我已经勾选了登录时启动
<img width="1106" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/31479141/10c607f8-8210-463e-95ff-7f5ecd9f4d42">
