### ISSUE TITLE
Safari浏览器中英文切换失败

### ISSUE THREAD

**Issue by noby338** [leaves615/KeyboardHolder#148]
Safari浏览器网页中(地址栏除外)，英文输入法切换到搜狗中文会切换失败(尽管系统菜单栏已显示切换)
Safari版本 17.3.1
macOS版本 Sonoma 14.3.1

**Comment by leaves615** [comment]
搜狗有内置中英文切换，如果使用本软件进行自动切换，建议关闭搜狗输入法内置的中英文切换功能。

**Comment by noby338** [comment]
<img width="800" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/01cc94e2-3511-4fb5-a44f-0d837f20e171">
<img width="800" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/0d6a4f95-589d-43f7-b492-b3671795e5f9">
<img width="540" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/703dff70-81db-46c2-b577-4a16b9c463e8">
<img width="540" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/1f2ed688-ecd4-42f9-94df-60c074312849">
<img width="540" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/33ee6f1e-7e24-429a-ac22-9f4473033d4b">




我的设置如图，在KeyboardHolder中设置了通过快捷方式切换系统英文和搜狗中文，同时KeyboardHolder设置了应用切换到Safari时自动切换搜狗。搜狗关闭了中英文切换的快捷键，关闭了自动切换英文。
1、当我切换应用到Safari(网页)时，KeyboardHolder自动切换到搜狗生效，中文正常输入，此时的菜单栏输入法图标中，搜狗输入法处于可用状态。
<img width="165" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/f8893d43-c431-4c31-8065-725c3e80c5b3">
2、当我在safari(网页)通过KeyboardHolder绑定的快捷切换到英文，再切换到中文时，中文输入为英文字母，此时的菜单栏输入法图标中，搜狗输入法处于不可用状态。
<img width="165" alt="图片" src="https://github.com/leaves615/KeyboardHolder/assets/87303763/7f3597cc-a5d7-43da-9e54-d2484ba72160">
3、当我在safari(网页)中通过macos系统中输入法快捷键切换到搜狗输入法时，中文正常输入，此时的菜单栏输入法图标中，搜狗输入法处于可用状态。
4、当我在safari(地址栏)通过KeyboardHolder绑定的快捷切换到英文，再切换到中文时，中文正常输入，此时的菜单栏输入法图标中，搜狗输入法处于可用状态。

**Comment by leaves615** [comment]
这个问题在网络有相关讨论。Carbon接口对CJKV第三方输入法的兼容BUG，我使用apple自带的拼音输入法未遇到过这个问题。尝试了多个方法都没有一个满意的办法能彻底修复该问题。目前选择了一个在我本地运行效果过得去的修复方案。我测试几天，如果没什么大问题话，将作为发布新版本更新。

**Comment by leaves615** [comment]
已发布新版本，新版本解决了该问题。

**Comment by noby338** [comment]
![Safari浏览器 2024-3-15](https://github.com/leaves615/KeyboardHolder/assets/87303763/b791be1e-6f21-4aeb-97d3-dfb802dd9839)

我更新了之后，重启电脑，问题仍然存在啊

**Comment by leaves615** [comment]
窗口切换应该没问题吧，快捷键的切换还是存在问题。

**Comment by leaves615** [comment]
safari 上这个问题，Apple 已经在启用carbon 接口，期待新的api修复CJKV输入法的问题了。
