### ISSUE TITLE
疑似bug报告

### ISSUE THREAD

**Issue by Stamptax** [leaves615/KeyboardHolder#149]
首先感谢作者开发了这一款软件，有时候真的非常有帮助。

不过在这里主要想说的还是偶尔会遇到的bug（也许是特性？因为我也不知道它的工作原理）

输入法方面我是用的是鼠须管，可以通过shift键来在这个输入法内切换中英文，同时我还使用了原生的英文输入法

具体问题集中出现在Domain里，输入法无法跟随网址切换
案例1. 使用浏览器时，在address bar使用了原生英文输入法，然后回到设置了中文输入的对应网页时，输入法没有自动切换为中文，而是保持了原生英文输入法
案例2. 给域名A设置中文输入法，域名B设置原生英文输入法。实际使用时输入法也不跟随网页不同而自动切换
（*.xxx.com和xxx.com的格式全都试过）

如果能有劳作者百忙之中抽空调查，那就感激不尽了

**Comment by leaves615** [comment]
请参照 #56  提供详细内容。

**Comment by Stamptax** [comment]
1. 输入法不跟随域名切换
2. 版本：1.12.12（81）
3. macOS 14.4
4. 开启address bar英文，在地址栏用英文输入，在（比如设置了百度贴吧使用中文）贴吧进行搜索仍然是英文； 在ChatGPT对话下设置了英文，在贴吧使用中文完毕后切换网页到ChatGPT对话，仍然是中文
5. 数据未找到
6. 否

**Comment by Stamptax** [comment]
> 域名匹配切换，需要启用了辅助控制。

谢谢。想请问什么是辅助控制？是macOS的辅助功能里的某个项目还是软件里的某个特定功能，还烦请赐教

**Comment by leaves615** [comment]
<img width="715" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/375323/20abbb0c-8f90-45d4-a522-f42c358a8086">

**Comment by Stamptax** [comment]
> <img width="715" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/375323/20abbb0c-8f90-45d4-a522-f42c358a8086">
> 
> 

非常感谢您的耐心与回复，谢谢
