### ISSUE TITLE
开机自启动异常

### ISSUE THREAD

**Issue by jqtmviyu** [leaves615/KeyboardHolder#152]
os: 12.7
app: 1.12.13(82)
问题描述: 开机自启异常
现象: 每次开机总是vscode自动打开该文件

![图片](https://github.com/leaves615/KeyboardHolder/assets/19925192/7296a7d4-4d6c-45f8-a5ab-23a3faadb02c)

解决方案:  退回旧版本1.12.7恢复正常.

update:

v1.12.14  同样自启有问题

**Comment by leaves615** [comment]
登录时启动与 VScode 没关系呀

**Comment by jqtmviyu** [comment]
> 登录时启动与 VScode 没关系呀

估计和我把 `shell` 脚本设置默认打开方式为vscode有关. 
1.12.7 之后应该是修改了自启方式.KeyboardHolder被识别成shell, 调用默认打开方式vscode. 

1.12.7  倒是一切正常.

**Comment by leaves615** [comment]
登录时启动基于 launchdeamon 的。
