### ISSUE TITLE
【bug】用自定义快捷键从英文状态下切换输入法，在某些场景下不生效

### ISSUE THREAD

**Issue by 5mdld** [leaves615/KeyboardHolder#16]
系统版本：macOS 11.5.2
型号：Mac mini (M1, 2020)
keyboardholder: 1.3.2
问题：从英文状态下，通过自定义快捷键切换输入法至中文或日文（其他未尝试）时，在某些场景下输入法指示器显示已切换，但是实际上未生效，打出来的还是英文。
有问题的场景：Safari里Google和百度的搜索框，Github等
无问题的场景：QQ以及微信聊天框，备忘录，Safari地址栏等

**Comment by leaves615** [comment]
非常感谢你的反馈。我会持续跟踪反馈的问题。
为了能够解决软件使用过程中的问题，需要了解一下进一步信息，能够帮助我更精准的分析和解决bug：
请问你的中文、日文输入法是macOS自带的还是第三方软件？

**Comment by 5mdld** [comment]
你好，输入法都是系统自带，尝试过第三方输入法（搜狗）也有同样的问题。
而且只从英文状态下通过自定义快捷键切换有这样的问题。从中文切换到日语（或者反向）、通过键盘的地球仪键以及系统自带的输入法切换快捷键切换时没有问题。

**Comment by leaves615** [comment]
麻烦把app的运行日志发给我 leaves615#gmail.com。可以的话，告诉我问题时间点。

**Comment by leaves615** [comment]
你应该是没有启用辅助功能吧。启用辅助功能，可以提升更多的切换效果。
![image](https://user-images.githubusercontent.com/375323/129364313-237e7a3d-c1bf-4590-9718-73fd5b14a694.png)

**Comment by 5mdld** [comment]
您好，邮件已发送，请查收。
ps：辅助功能是启用状态

**Comment by 5mdld** [comment]
查了下是macOS的远古bug，暂时的解决方法是连按两次“英数键”再切换，希望苹果有朝一日能修复吧。

**Comment by leaves615** [comment]
![image](https://user-images.githubusercontent.com/375323/130376543-3bbe1a8f-bb1b-4704-9363-88a8136dce47.png)
可以试试取消红框中的两个功能的勾选。
