### ISSUE TITLE
可以在准备输入的时候提下一下当前的输入法吗？

### ISSUE THREAD

**Issue by ETHANSHAW** [leaves615/KeyboardHolder#160]
在用中文输入法的时候会用shift切换中英文，但是mac状态栏输入法图标是固定的，导致在准备输入的时候不知道当前是中文还是英文，经常输了一大串发现都错了。希望添加在点击输入框或者在word里准备输入的时候先提示一下当前的输入法。非常感谢啦

**Comment by leaves615** [comment]
可以开启输入法提示
