### ISSUE TITLE
DBeaver 配置切换输入法并未生效

### ISSUE THREAD

**Issue by ZhangYanFFF** [leaves615/KeyboardHolder#162]
DBeaver 配置切换输入法并未生效，其他软件配置均正常。
DBeaver版本：24.0.5
keyboardHolder版本：1.12.19 (88)
macos:14.5

<img width="764" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/55775234/45307832-ac2d-45cc-b2be-6b56d651ada6">
<img width="581" alt="image" src="https://github.com/leaves615/KeyboardHolder/assets/55775234/d4c1fe27-eb27-4d8e-925d-94013bdeb0c0">

**Comment by leaves615** [comment]
请参照 #56  提供更多信息。

**Comment by leaves615** [comment]
This issue has been resolved in [Release v1.13.0](https://github.com/leaves615/KeyboardHolder/releases/tag/v1.13.0).
