### ISSUE TITLE
域名匹配不生效

### ISSUE THREAD

**Issue by Choumode** [leaves615/KeyboardHolder#165]
1. 问题描述
域名匹配功能一直不生效，在不同的应用版本和系统版本下都是这样

2. 应用版本
1.12.19(88)

3. 操作系统版本
macOS 15.0

4. 问题可复现的操作步骤
在设置了填写了域名后打开浏览器访问该网站，仍然无法自动切换（例如*.baidu.com和baidu.com均尝试过）

5. 问题时段和日志文件
[cn.leaves.KeyboardHolder 2024-06-13--03-24-49-268.log](https://github.com/user-attachments/files/15813616/cn.leaves.KeyboardHolder.2024-06-13--03-24-49-268.log)

6. 是否启用了辅助控制
是

**Comment by leaves615** [comment]
你浏览器的界面语言是简体中文，还是英文？

**Comment by Choumode** [comment]
> 你浏览器的界面语言是简体中文，还是英文？

简体中文

**Comment by leaves615** [comment]
新版应该可以解决该问题，如果还是不行请留言。

**Comment by Vvictorli** [comment]
> 新版应该可以解决该问题，如果还是不行请留言。

应用版本
1.12.20(89)

操作系统版本
macOS 12.3 (21E230)

重启应用生效，运行一段时间又不好使了

**Comment by leaves615** [comment]
请提供下不好使的时候的日志文件。谢谢

**Comment by Choumode** [comment]
> 新版应该可以解决该问题，如果还是不行请留言。

您好，新版本仍然不起作用，我已尝试过重新启动程序，在设置里删除后又重新添加辅助控制，均不起作用。
<img width="912" alt="截屏2024-07-27 20 29 51" src="https://github.com/user-attachments/assets/e8e8072a-f7ce-4136-9e99-549abb966c98">
我使用的是最新版Chrome浏览器，系统为macOS 15.0 DB4，以下是我近期的使用日志。
[cn.leaves.KeyboardHolder 2024-07-23--14-52-49-102.log](https://github.com/user-attachments/files/16400196/cn.leaves.KeyboardHolder.2024-07-23--14-52-49-102.log)
[cn.leaves.KeyboardHolder 2024-07-24--15-08-30-056.log](https://github.com/user-attachments/files/16400197/cn.leaves.KeyboardHolder.2024-07-24--15-08-30-056.log)
[cn.leaves.KeyboardHolder 2024-07-25--15-08-45-913.log](https://github.com/user-attachments/files/16400199/cn.leaves.KeyboardHolder.2024-07-25--15-08-45-913.log)

**Comment by leaves615** [comment]
This issue has been resolved in [Release v1.13.0](https://github.com/leaves615/KeyboardHolder/releases/tag/v1.13.0).
