### ISSUE TITLE
开机启动功能失灵

### ISSUE THREAD

**Issue by unixq** [leaves615/KeyboardHolder#166]
你好，非常感谢开发者制作的这个软件，减少了我切换输入法的烦恼，提高的办公效率。
目前我有发现到一个小问题，在我的mac OS 11.7.10上，无法伴随电脑自动启动，即便是软件内打开了开机启动的选项。
我也启用了辅助控制功能。还请开发者协助看下，再次感谢！

**Comment by Superoutman** [comment]
我也有同样困扰，貌似是最近几个版本开始的？

**Comment by leaves615** [comment]
手上没有能运行macos11的机器了，无法验证该问题。 建议关闭app自带的自动启动，改用系统提供的登录时启动。一样可以实现自动启动的目标

PS：那位能告诉我怎么在 M系列机器上通过parallels 来安装它。

**Comment by Jonnyan404** [comment]
从1.12.7版本之后开始,软件自带的开机启动功能,就没有完全正常过...    m1 14.6.1
