### ISSUE TITLE
关于输入法提示窗口大小

### ISSUE THREAD

**Issue by hshsilver** [leaves615/KeyboardHolder#167]
作者您好，目前的输入法提示功能很棒，美中不足是窗口整体大小（包括图标和文字）对于视力不好的人来说稍微有点小。

请问是否考虑增加一个自定义缩放功能？

例如能自定义缩放到1-5倍？谢谢！

**Comment by leaves615** [comment]
This issue has been resolved in [Release v1.13.0](https://github.com/leaves615/KeyboardHolder/releases/tag/v1.13.0).
