### ISSUE TITLE
新版设置导入/导出功能bug，导入无法选文件 

### ISSUE THREAD

**Issue by sunrisewestern** [leaves615/KeyboardHolder#170]
导入无法选中导出的.dat文件

**Comment by leaves615** [comment]
麻烦提供更多的问题信息

**Comment by sunrisewestern** [comment]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/8bbcf0b2-2e21-4cbc-b026-77b00e68b36e">
红框内是导出的config.dat 文件，导入时是灰色的无法选中

**Comment by leaves615** [comment]
哪个版本的系统？

**Comment by leaves615** [comment]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/60208d14-0688-4e1c-a01f-c070cd1d6597">
我的是可以正常选择

**Comment by sunrisewestern** [comment]
sonoma 14.5, 刚升了14.6 也不行

**Comment by sunrisewestern** [comment]
Apple M1 Pro
