### ISSUE TITLE
有时候会自动退出，最近几个版本出现的

### ISSUE THREAD

**Issue by Ineffable919** [leaves615/KeyboardHolder#175]
最新版  1.13.3   macOS 14.5

**Comment by Ineffable919** [comment]
[Uploading cn.leaves.KeyboardHolder 2024-09-12--09-22-34-683.log…]()

**Comment by Ineffable919** [comment]
崩溃日志

**Comment by leaves615** [comment]
更新新版本，看是否还会崩溃

**Comment by Ineffable919** [comment]
> 更新新版本，看是否还会崩溃

👌

**Comment by xuelingkang** [comment]
问题描述：运行一段时间后，应用未响应
应用版本：1.13.5
系统版本：14.6.1
日志：[cn.leaves.KeyboardHolder 2024-09-29--01-57-26-245.log](https://github.com/user-attachments/files/17177739/cn.leaves.KeyboardHolder.2024-09-29--01-57-26-245.log)
