### ISSUE TITLE
idea 无法正常切换输入法

### ISSUE THREAD

**Issue by songhao8080** [leaves615/KeyboardHolder#18]
系统版本：big sur 11.6
 		 MacBook Pro (Retina, 15-inch, Mid 2015)
![image](https://user-images.githubusercontent.com/10607039/133545129-453c18de-ebe1-4765-9c9f-6dd25f929333.png)
设置的是百度输入法，但是每次到编辑器都切换到自带的英文输入法

**Comment by songhao8080** [comment]
已解决,idea 插件导致的

**Comment by sunanan** [comment]
我也遇到了同样的问题。
但是只是默认安装，没有特别安装什么插件。
请问您是怎么解决的？哪个插件导致的？
