### ISSUE TITLE
输入法快捷键失效

### ISSUE THREAD

**Issue by liuxindtc** [leaves615/KeyboardHolder#184]
macos：15.2
输入法：百度输入法
描述：英文状态下，使用输入法快捷键直接切换到中文。这个时候出现系统的切换提示标志，变成中文且状态也显示中文。但此时输入还是英文。使用输入法快捷键继续切换英文再中文，同样出现有效提示，但是输入法始终英文不变。
这个情况下使用系统的输入法切换快捷键切换到英文之后，再使用输入法快捷键切换又有效了。感觉上就是输入法快捷键用了多次或长时间使用之后，就失效了，只变化提示，不变化输入法。

3Q！

**Comment by leaves615** [comment]
macos 输入法的api存在这个bug，apple不推出新的api。这个问题无能为力。

**Comment by liuxindtc** [comment]
> macos 输入法的api存在这个bug，apple不推出新的api。这个问题无能为力。

🫡收到，bug只能等他修复了。
