### ISSUE TITLE
嘿 ，出了个显示bug。如图

### ISSUE THREAD

**Issue by xSeaGull** [leaves615/KeyboardHolder#19]
![image](https://user-images.githubusercontent.com/43143262/139258448-ad4341c3-1a78-4c2a-aba6-8d91f6e91e01.png)

**Comment by leaves615** [comment]
感谢反馈。
请问：
1. app版本？
2. os版本？

**Comment by xSeaGull** [comment]
@leaves615 

app版本：1.3.2
os版本：big sur 11.6

**Comment by xSeaGull** [comment]
话说 大佬会适配 12.0吗

**Comment by leaves615** [comment]
我现在用的是12.0系统。 正常运行。

> 话说 大佬会适配 12.0吗
