### ISSUE TITLE
MacOS Monterey 下，通过 brew 安装后，打开报错

### ISSUE THREAD

**Issue by crown3** [leaves615/KeyboardHolder#20]
![image](https://user-images.githubusercontent.com/19649900/143182189-9839f83f-e4d4-4a00-8c94-2a790524a3a8.png)
不清楚还需要提供什么信息，来帮忙修复这个 bug
PS：通过 v站上面的发帖找过来的

**Comment by crown3** [comment]
是我自己的问题，没细看这个问题的解决方案，请忽略该 issue
https://support.apple.com/en-ph/guide/mac-help/mchleab3a043/mac

**Comment by leaves615** [comment]
brew 脚本是网友提供的脚本。
为保证可信安装建议在github下载安装。
感谢支持。
