### ISSUE TITLE
使用 alt-tab-macos 切换窗口，会失效，大佬～

### ISSUE THREAD

**Issue by Suscc** [leaves615/KeyboardHolder#21]
https://github.com/lwouis/alt-tab-macos

望大佬解决～

**Comment by leaves615** [comment]
安装了 alit-tab  暂时没有发现 切换输入法失效点问题。持续关注。

感谢反馈。

**Comment by cmicat** [comment]
复现步骤

1. 打开一个文本编辑器，比如 mac 自带的 "文本编辑"。这个里面设置为搜狗拼音输入法
2. 打开另外一个文本编辑器，比如 "Sublime Text"。这个里面设置为英文输入法
3. 使用 AltTab 这个应用的切换窗口功能，也就是狂按 Alt+Tab 快捷键。
4. 然后就会发现两个应用的输入法都变成英文了。

**Comment by leaves615** [comment]
感谢细节的反馈，后续会测试，验证以及修复。
