### ISSUE TITLE
选择了隐藏状态栏图标后就再也找不到软件运行的窗口了

### ISSUE THREAD

**Issue by rockjava** [leaves615/KeyboardHolder#24]
选择了隐藏状态栏图标后就再也找不到软件运行的窗口了，重新安装也不好用了，这个这么解决啊？

**Comment by leaves615** [comment]
只能kill 进程，这个功能考虑不周。

**Comment by gonejack** [comment]
新版Macbook的刘海的设计搞得得隐藏掉部分图标，然后发现这个隐藏了就再也无法打开设置了。

**Comment by gonejack** [comment]
删掉配置文件
```
rm ~/Library/Preferences/cn.leaves.KeyboardHolder.plist
```
再杀掉进程可以解决。

**Comment by leaves615** [comment]
请使用下载使用新版本。隐藏后可通过快捷键重新激活显示。

**Comment by wzsjackson** [comment]
胡说快捷键是啥。。。看过一遍忘了。。。

**Comment by leaves615** [comment]
> 胡说快捷键是啥。。。看过一遍忘了。。。

菜单隐藏功能，在app重新启动后会恢复菜单栏显示。

**Comment by wzsjackson** [comment]
> > 胡说快捷键是啥。。。看过一遍忘了。。。
> 
> 菜单隐藏功能，在app重新启动后会恢复菜单栏显示。

哦哦，我傻傻的重装了一次，哈哈
