### ISSUE TITLE
在 Launchpad 应用下无效

### ISSUE THREAD

**Issue by AnyOfYou** [leaves615/KeyboardHolder#27]
先感谢作者的开发工作。

发现在 Launchpad 应用下软件没能起作用。我设置在 Launchpad 下永远使用英文，但切换到 Launchpad 后（通过触摸板手势触发），还是会为切换前的应用的输入法状态（如之前在 Safari 下，为中文输入法状态，触发 Launchpad，依然是中文）。

尝试过重启电脑，无效。尝试用 Applications 文件夹内点击图标的方式来触发 Launchpad，无效。打开软件内的切换提示，触发 Launchpad 后，并无输入法切换提示。系统版本 10.15.7。

一番搜索后，我发现这个问题在同类型的工具软件 [SwitchKey 中也存在](https://github.com/itsuhane/SwitchKey/issues/4)，从作者的解释看，看上去暂时无法解决了。

**Comment by leaves615** [comment]
Launchpad 为系统应用。目前没有方法可以感知它的运行状态。所以没办法为它进行输入法控制。
