### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by qiaotian-huang** [leaves615/KeyboardHolder#30]
系统: 12.1

软件版本：1.5.0

![image](https://user-images.githubusercontent.com/96474288/146917580-ac6ae747-af77-48e9-8666-5c9996d0a091.png)

**Comment by leaves615** [comment]
这个是显而易见的bug，列表采用标准的swiftui 的list。无法复现此问题。

**Comment by qiaotian-huang** [comment]
> 这个是显而易见的bug，列表采用标准的swiftui 的list。无法复现此问题。

我这边开机之后，打开monitor，再打开一个别的程序，然后在自定义app里面按加号，monitor的高度都是异常的，重启电脑也是这样。
