### ISSUE TITLE
勾选系统偏好设置中的“自动切换到文稿的输入法”就可以记忆 App 的输入法啊

### ISSUE THREAD

**Issue by GanZhiXiong** [leaves615/KeyboardHolder#31]
![image](https://user-images.githubusercontent.com/27394631/146934475-c1ffc469-b1d6-4863-a748-27b1627b9dcb.png)

我想知道你这个软件和系统偏好设置中的“自动切换到文稿的输入法”有什么区别？

**Comment by leaves615** [comment]
系统偏好设置中的“自动切换到文稿的输入法” 有一定时效期的，超过时效期的app被激活后，它不会按照预期的去切换输入法。

**Comment by GanZhiXiong** [comment]
好像只有关闭App的后才会失效吧，重新打开 App 是不会使用上次使用的输入法的。

**Comment by GanZhiXiong** [comment]
你这个软件能在 App 重新打开后也使用 App 上次的输入法吗？

**Comment by leaves615** [comment]
配置 app 在启动时默认使用的输入法。
在 app 来回切换后能够记忆被切换到后台前使用的输入法，并在 app 再次激活后自动切换之前使用的输入法。
可针对指定 app 配置启动时默认输入法，或者配置 app 每次激活的默认输入法。
输入法切换提示。
输入法自定义切换快捷键。
支持 alfred 的输入法切换。
支持记忆聚焦搜索的输入法。

**Comment by GanZhiXiong** [comment]
1. 能记忆同一个 App 不同文本框的输入法吗？因为“自动切换到文稿的输入法”就能做到。
2. 能识别搜狗的中英文输入法吗？

**Comment by leaves615** [comment]
1. 见仁见智。
2. 暂时不考虑该功能。
