### ISSUE TITLE
输入法记忆功能出现bug

### ISSUE THREAD

**Issue by rrriiicccooo** [leaves615/KeyboardHolder#33]
使用2021款m1max运行macOS 12.1
软件版本1.5.2

软件设置英文abc为新应用启动时的默认输入法
在自定义规则中添加Safari默认输入法为abc，**没有**勾选“每次切换使用默认输入法”
实际使用中有时启动Safari时默认输入法为拼音，但是切换其他应用后切换回Safari变为abc；有时启动Safari输入法正常切换到默认abc输入法，手动切换拼音输入法后再切换应用，回到Safari便变成了abc输入法。

不知道我是否表述清楚了，总结就是如果某个应用不勾选“每次切换使用默认输入法”的话，输入法在切换应用后表现非常混乱不稳定。
其他应用比如pages，备忘录，notion等也存在同样的问题

**Comment by rrriiicccooo** [comment]
同时Safari应用中似乎Safari的地址栏和Safari的网页部分被当成两个独立应用运行了，比如在网页主体内是abc输入法但是点击地址栏后会自动跳转到拼音输入法，这个问题同样也会造成safari切换应用后自动切换输入法的逻辑混乱

**Comment by leaves615** [comment]
Safari 我测试没暂时没遇到类似问题。我会多使用测试。
