### ISSUE TITLE
是否可以去掉默认的美国输入法？

### ISSUE THREAD

**Issue by mining-id** [leaves615/KeyboardHolder#35]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/94845005/152643275-0289e66c-2706-4ff8-9ea0-7cbff80967d5.png">

非常感谢！

**Comment by leaves615** [comment]
macOS至少需要一个基础输入法。 
不过可以换其他的。比如abc

**Comment by mining-id** [comment]
@leaves615  明白了，感谢回复！
