### ISSUE TITLE
重启后，显示设定界面，能否设置为隐藏？

### ISSUE THREAD

**Issue by ansonliao** [leaves615/KeyboardHolder#42]
更新到最新版后，电脑每次重启后，都会显示设定界面，能否设置为隐藏？
谢谢！

<img width="798" alt="image" src="https://user-images.githubusercontent.com/6060224/159399058-3eda32cc-94d9-4c5e-921d-52f7a63fa669.png">

**Comment by JunweiZheng93** [comment]
+1，有相同的需求

**Comment by wushuai111** [comment]
+1

**Comment by EugeneHo1** [comment]
+1
