### ISSUE TITLE
关于软件版本号的疑问？

### ISSUE THREAD

**Issue by zhouxiongh** [leaves615/KeyboardHolder#45]
找不到反馈的地方就发在这里了
首先，感谢作者的付出，软件方便、稳定，简洁；符合优秀工具软件的基本要素
其次，有一点疑问，为什么修订号递增会增加新的功能？

**Comment by leaves615** [comment]
感谢提醒，发布后我也是发现了这个问题。已经发布了，就没有撤销了。

foobell ***@***.***> 于2022年3月26日周六 21:24写道：
