### ISSUE TITLE
切换输入法abc的时候总是不提示

### ISSUE THREAD

**Issue by mycherish** [leaves615/KeyboardHolder#46]
简体拼音是可以显示切换提示的

**Comment by leaves615** [comment]
感谢反馈问题。
为了进一步分析问题，需要知道：
1. 当前使用的版本。
2. 当前操作系统的版本。
3. 问题复现的步骤。

**Comment by mycherish** [comment]
版本1.5.4

**Comment by mycherish** [comment]
应用版本：1.5.4
系统版本：macOS 12.3
点击键盘中英切换按键，切换成简体拼音会有提示框，切换成ABC不显示提示框

**Comment by leaves615** [comment]
1.5.5 版本已修复

**Comment by mycherish** [comment]
好的，已更新
