### ISSUE TITLE
单个应用设置太麻烦了,能不能加个所有用切换都自动切换输入法的设置

### ISSUE THREAD

**Issue by gedoor** [leaves615/KeyboardHolder#50]
针对所有应用的设置只有首次启动默认输入法,切应用需要单独设置,希望添加个所有设置

**Comment by leaves615** [comment]
所有应用在启动时、激活时都切换到指定的输入法？

**Comment by gedoor** [comment]
是的,所有应用启动激活时都自动切换,现在激活时切换只能单独设置

**Comment by leaves615** [comment]
激活的时候，没有自定义配置的app会自动切换app切换到不活跃时所用的输入法。

**Comment by gedoor** [comment]
只想用搜狗输入法,shift切换中文和英文,自带的abc不好用,但是有时候会按错,shift切换半天一看是自带的abc输入法

**Comment by gedoor** [comment]
要是能简单的把abc删了,我都想删了自带的abc输入法

**Comment by leaves615** [comment]
> 要是能简单的把abc删了,我都想删了自带的abc输入法

第三方输入法会不同程度地收集使用者的信息，相对不太放心。系统自带的输入法，现在也是越来越好用了。


自带的可以删除的，网络有方法：
https://blog.51cto.com/u_11440114/3005141

**Comment by leaves615** [comment]
1.6.0 已版本支持

**Comment by gedoor** [comment]
感谢
