### ISSUE TITLE
spotlight想单独设置发现找不到

### ISSUE THREAD

**Issue by kelenkai** [leaves615/KeyboardHolder#51]

**Comment by leaves615** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/375323/163679696-59aa2003-8cba-44a7-932b-de276a33051d.png">

**Comment by kelenkai** [comment]
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/375323/163679696-59aa2003-8cba-44a7-932b-de276a33051d.png">

感谢大佬哈哈，大佬继续干巴爹
