### ISSUE TITLE
mac重新启动后自定义app规则偶尔会清空

### ISSUE THREAD

**Issue by rrriiicccooo** [leaves615/KeyboardHolder#53]
版本1.6，macOS 12.3.1

**Comment by leaves615** [comment]
感谢你的反馈。我会持续关注这个问题。

**Comment by rrriiicccooo** [comment]
感谢回复，补充说明，两次清空发生在无网络环境下的重启

**Comment by mushanshanshan** [comment]
补充：

**Comment by leaves615** [comment]
请更新新版本1.6.1。看看是否还会存在同样的问题。

**Comment by leaves615** [comment]
1.6.0 版本更新了自定义应用配置的结构，旧版本的配置做了兼容转换处理。 被清空的问题，应该是兼容转换处理失败导致的。暂时无法定位原因。
