### ISSUE TITLE
问题反馈必读

### ISSUE THREAD

**Issue by leaves615** [leaves615/KeyboardHolder#56]
为了更精准分析您遇到的问题。在填写时候请提供一下信息：

1. 问题描述
2. 应用版本
3. 操作系统版本
4. 问题可复现的操作步骤
5. 问题时段和日志文件（可在 `/Users/<username>/Library/Logs/KeyboardHolder` 中找到）
6. 是否启用了辅助控制

**Comment by iRubbish** [comment]
Alfred设置了自动切换输入法不生效
1.10.3
13.2
添加应用设置输入法规则，打开Alfred应用不管是搜索还是进入应用界面都未生效
日志路径未找到 KeyboardHolder
启用了辅助控制，企微跟iterm2 正常

**Comment by iRubbish** [comment]
> Alfred设置了自动切换输入法不生效 1.10.3 13.2 添加应用设置输入法规则，打开Alfred应用不管是搜索还是进入应用界面都未生效 日志路径未找到 KeyboardHolder 启用了辅助控制，企微跟iterm2 正常

使用了一下其他的平替软件可以的，求大佬有空看看能不能修复一下

**Comment by leaves615** [comment]
@iRubbish 下一版本修复
