### ISSUE TITLE
使用自动操作创建脚本形式启动app不可用

### ISSUE THREAD

**Issue by D0ngsec** [leaves615/KeyboardHolder#57]
为了更精准分析您遇到的问题。在填写时候请提供一下信息：

问题描述：
我使用自动操作创建脚本形式创建了app，并启动app。但是使用keyboardholder不可以切换输入法，但是switchkey可以。
应用版本：
<img width="260" alt="image" src="https://user-images.githubusercontent.com/26764349/166864797-453fce5f-4c2c-48de-abe4-724efbb4a5df.png">

操作系统版本：
macos 12.3.1
问题可复现的操作步骤：
自动操作创建脚本形式创建了app，并启动app。并在keyboardholder中配置。无法生效。
问题时段和日志文件（可在 /Users/leaves/Library/Logs/KeyboardHolder 中找到）：
不存在日志文件

是否启用了辅助控制：
是，其他软件使用无问题。

**Comment by leaves615** [comment]
可以提供你的自动操作脚本吗？

**Comment by D0ngsec** [comment]
> 可以提供你的自动操作脚本吗？

就简单的sh脚本（如下）：

java -jar xxx.jar
