### ISSUE TITLE
cap lock switch ？

### ISSUE THREAD

**Issue by zsmatrix62** [leaves615/KeyboardHolder#59]
为什么我用大写锁定键会自动切换中英文输入法？没有地方可以设置么。

**Comment by zsmatrix62** [comment]
只有暂时先卸载了 。。。之前用的好好的，更新后就这样了。

**Comment by leaves615** [comment]
应用不涉及到大写锁定键。 检查输入法配置参数。
<img width="262" alt="image" src="https://user-images.githubusercontent.com/375323/168413110-64d50929-ca38-4d36-9d78-c3512c04b1c1.png">

**Comment by zsmatrix62** [comment]
> 应用不涉及到大写锁定键。 检查输入法配置参数。
> 
> <img width="668" alt="image" src="https://user-images.githubusercontent.com/375323/168413131-fa54ca3e-d113-4356-8a99-678d87b7e171.png">
> 
> 

好像是乌龙了.. 今天更新了beta版系统那个选项不起作用了，默认就是大小写键切换。😭
