### ISSUE TITLE
Input method switching prompt 的寬度未隨名稱改變

### ISSUE THREAD

**Issue by stevenwdhu** [leaves615/KeyboardHolder#60]
<img width="206" alt="image" src="https://user-images.githubusercontent.com/30546031/168971015-44b6f4ad-34a4-4e79-bfad-41341ad7596e.png">
<img width="189" alt="image" src="https://user-images.githubusercontent.com/30546031/168971083-867d6f89-9011-40a7-ba7c-2dc0b6911a54.png">
如上圖，部分輸入法名稱未能顯示完全。

**Comment by leaves615** [comment]
新版本以修正。
