### ISSUE TITLE
自动更新每个版本都会出错。

### ISSUE THREAD

**Issue by uclort** [leaves615/KeyboardHolder#61]
干脆上 brew 吧。

**Comment by leaves615** [comment]
brew install --cask keyboardholder

网络错误还是什么？

**Comment by uclort** [comment]
> brew install --cask keyboardholder
> 
> 网络错误还是什么？

https://cdn.jsdelivr.net/gh/uclort/file@master/uPic/Xnip2022-05-24_14-56-44.png

**Comment by leaves615** [comment]
非常感谢反馈，检查后发现自动更新链接错误，导致更新错误。现已修正。

**Comment by zhangyulai** [comment]
brew上的不是最新版本，该怎么升级呢？

**Comment by leaves615** [comment]
我将提交pull request。
