### ISSUE TITLE
1.6.2 输入法名称过长问题

### ISSUE THREAD

**Issue by dufu1991** [leaves615/KeyboardHolder#62]
我用的是鼠须管，名称也就三个字，切换的时候输入法名称显示不全。
我看这个版本说明是修复这个问题，奇怪的是之前没问题，反而是我更新了这个版本后出现这个问题。

**Comment by leaves615** [comment]
为了更精准分析您遇到的问题。在填写时候请提供一下信息：

问题描述
应用版本
操作系统版本
问题可复现的操作步骤
问题时段和日志文件（可在 /Users/<username>/Library/Logs/KeyboardHolder 中找到）
是否启用了辅助控制
