### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by aLIEz-xue** [leaves615/KeyboardHolder#63]
在浏览器下载后，存放在下载文件夹，再从下载文件夹拖到应用程序文件夹中，再打开软件，检查更新报错

![image](https://user-images.githubusercontent.com/59567929/171339247-6013f68a-0117-49f5-8f47-6beec7a80d44.png)

**Comment by leaves615** [comment]
操作系统版本？
app版本？ 1.6.2？
app路径？/Applications/   ?

aLIEz-xue ***@***.***>于2022年6月1日 周三16:36写道：

**Comment by aLIEz-xue** [comment]
> 操作系统版本？ app版本？ 1.6.2？ app路径？/Applications/ ? aLIEz-xue ***@***.***>于2022年6月1日 周三16:36写道：
> […](#)

![image](https://user-images.githubusercontent.com/59567929/171364233-fb6889f6-b790-46ba-b47f-1945c02d2c66.png)
![image](https://user-images.githubusercontent.com/59567929/171364329-274cbf4a-c2ea-40a6-bcca-752219a22585.png)

**Comment by leaves615** [comment]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/375323/171367690-7ff90721-3c84-4469-8e06-f2afaf7aaab6.png">
通过查看进程的详情信息，判断app所在的位置。

**Comment by aLIEz-xue** [comment]
> <img alt="image" width="1252" src="https://user-images.githubusercontent.com/375323/171367690-7ff90721-3c84-4469-8e06-f2afaf7aaab6.png">
> 
> 通过查看进程的详情信息，判断app所在的位置。

不知道在哪
[活动监视器KeyboardHolder.txt](https://github.com/leaves615/KeyboardHolder/files/8812736/KeyboardHolder.txt)

**Comment by leaves615** [comment]
启动台 搜索“活动监视器”

<img width="565" alt="image" src="https://user-images.githubusercontent.com/375323/171369905-64d4263e-8cf6-4dab-a5f6-c1db7acec74c.png">

**Comment by leaves615** [comment]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/375323/171370129-d7e6ed4a-4da9-4746-83b1-4e7cd6721402.png">
红框的路径，就是启动的app真实的路径。

并不是在/Applications/ 下启动的。

**Comment by aLIEz-xue** [comment]
> 启动台 搜索“活动监视器”
> 
> <img alt="image" width="565" src="https://user-images.githubusercontent.com/375323/171369905-64d4263e-8cf6-4dab-a5f6-c1db7acec74c.png">

我上传了 txt，就是活动监视器那里面的内容

**Comment by aLIEz-xue** [comment]
> 

为什么在那个路径呢

**Comment by leaves615** [comment]
用访达 进到/Applications/下，双击启动试试。


你有使用其他app管理工具？

**Comment by aLIEz-xue** [comment]
> 用访达 进到/Applications/下，双击启动试试。
> 
> 你有使用其他app管理工具？

找到原因了，我使用 qspace 接管了访达，在那里把文件拖到应用程序文件夹里，然后就不能更新，看了下其他通过此方式安装的软件，运行时都会运行在/private/var/folders/......的路径下，谢谢
