### ISSUE TITLE
状态栏图标隐藏问题

### ISSUE THREAD

**Issue by Zisbusy** [leaves615/KeyboardHolder#64]
软件设置开机自动启动，状态栏图标隐藏，重启开机时软件图标仍然会显示在状态栏上。

**Comment by leaves615** [comment]
是这样的。
避免隐藏后找不到显示菜单栏图标的入口，在应用启动时就默认显示菜单栏图标了。

**Comment by leaves615** [comment]
下个版本加个配置，启动时保持状态栏的图标隐藏状态。

**Comment by Zisbusy** [comment]
见过类似的，他们的逻辑是隐藏任务栏图标后可以点击应用图标打开控制界面或者显示导航栏图标。可以参考一下。

**Comment by leaves615** [comment]
> 

这种不回实现，搜索了下，也没找到这种效果的方法。

**Comment by Zisbusy** [comment]
看看这个能不能参考一下。https://github.com/Caldis/Mos

**Comment by leaves615** [comment]
> 看看这个能不能参考一下。https://github.com/Caldis/Mos

学习了对方的代码，没能用测试代码实现出你说的效果。

**Comment by Marsman1996** [comment]
不如再下一个Hidden Bar实现隐藏😂

**Comment by shruru** [comment]
我再这里求救一下，我设定了隐藏图标，现在想修改设置，但再次点击 App，不出现界面了。估计只能用快捷键呼出，但快捷键.....是什么？背不出来，这里页面上似乎也没写到。😂

**Comment by leaves615** [comment]
Command+Option+F11

> 我再这里求救一下，我设定了隐藏图标，现在想修改设置，但再次点击 App，不出现界面了。估计只能用快捷键呼出，但快捷键.....是什么？背不出来，这里页面上似乎也没写到。😂

**Comment by Anopia** [comment]
> Command+Option+F11

没有用。调不出来。请问怎么办呀？
