### ISSUE TITLE
输入法切换提示能否根据输入法名称内容长度自适应大小

### ISSUE THREAD

**Issue by qq420100523** [leaves615/KeyboardHolder#65]
目前使用最版本1.7.1，输入法切换到鼠须管输入法时，只显示了“鼠...”，无法完整显示输入法名称。
另：提示框大，提示内容少，显得不太美观，希望能优化一下，感谢开发者

**Comment by leaves615** [comment]
我装一个验证下

**Comment by leaves615** [comment]
<img width="168" alt="image" src="https://user-images.githubusercontent.com/375323/172752330-b981f00b-c0ac-495b-ab28-c07d82f43bf2.png">
最新的鼠须管输入法在我的电脑上显示正常。你系统版本是？

**Comment by qq420100523** [comment]
> <img alt="image" width="168" src="https://user-images.githubusercontent.com/375323/172752330-b981f00b-c0ac-495b-ab28-c07d82f43bf2.png">
> 
> 最新的鼠须管输入法在我的电脑上显示正常。你系统版本是？

我更新到最新版本1.8.0就正常了，可以显示完整名称，提示框也自适应了，非常美观
