### ISSUE TITLE
很好用 想有个 feature 不知道是否...

### ISSUE THREAD

**Issue by shruru** [leaves615/KeyboardHolder#66]
不知道是否要求过高：希望能否针对特定的 网站切换输入法？
例如 浏览器窗口是 baidu.com 就 中文
窗口是 youtube.com 就 英文...

是不是太难了...@_@ 
记得 keyboard mastre 那个似乎可以通过判定 Chrome 当前激活的标签页来做到

**Comment by shruru** [comment]
太棒了，我看到加了域名的支持，更棒的是！我完全不太会，请问有人给一个简单的指导怎么填吗
试了几个域名输入进去，似乎都无效😂

**Comment by leaves615** [comment]
支持safari, chrome, edge
规则  匹配域名
google.com -> google.com, www.google.com
*google.com -> mail.google.com

**Comment by shruru** [comment]
谢谢，Amazing！但刚刚发现一个小小的 bug，例如：
在一个设定好规则的浏览器 Tab 下，按全文搜索：Command+F ,会自动切换回 中文状态 ，总之不是当前的页面输入法状态.

**Comment by leaves615** [comment]
> 谢谢，Amazing！但刚刚发现一个小小的 bug，例如： 在一个设定好规则的浏览器 Tab 下，按全文搜索：Command+F ,会自动切换回 中文状态 ，总之不是当前的页面输入法状态.

感谢你的反馈。

**Comment by leaves615** [comment]
> 谢谢，Amazing！但刚刚发现一个小小的 bug，例如： 在一个设定好规则的浏览器 Tab 下，按全文搜索：Command+F ,会自动切换回 中文状态 ，总之不是当前的页面输入法状态.

这个bug已修复。请更新最新版本。
