### ISSUE TITLE
弹出式的应用切换，输入法切换逻辑有点混乱

### ISSUE THREAD

**Issue by dependentsign** [leaves615/KeyboardHolder#67]
比如我设置的欧路词典，我把它设置为启动和激活都是abc输入，但是当我使用command+control+c 激活light peek时候却是last used input method
激活这个litht peek 系统左上角的应用不会变化，跟长按command调出 cheatsheet一样
<img width="376" alt="Screen Shot 2022-06-11 at 20 39 58" src="https://user-images.githubusercontent.com/59330230/173188317-60518e09-e1f8-4474-a060-9c899fd44fb6.png">

**Comment by leaves615** [comment]
聚焦/alfred/raycast 这几种弹出式应用有没有同样的问题？

**Comment by dependentsign** [comment]
聚焦/Alfred都没有问题诶，我观察了一下，像是点击状态栏上的别的图标也会有输入法切换，比如点击 电池 图标、控制中心图标，貌似整个状态栏算是一个应用？

**Comment by leaves615** [comment]
状态栏应该属于独立进程的。 后续研究下。

dependentsign ***@***.***>于2022年6月11日 周六21:44写道：

**Comment by dependentsign** [comment]
好耶，辛苦了
