### ISSUE TITLE
搜狗输入法经常错乱

### ISSUE THREAD

**Issue by goodwenxi** [leaves615/KeyboardHolder#69]
自带的简体拼音输入法工作正常，但是换搜狗输入法后经常在 pinyin 和 abc 之间切换错乱

**Comment by leaves615** [comment]
如果你希望用KeyboardHolder来辅助你切换输入法。建议关闭第三方输入法的中/英切换功能。这样就不会导致错乱了。

**Comment by goodwenxi** [comment]
OK，我试试
