### ISSUE TITLE
建议添加应用的功能简化一点

### ISSUE THREAD

**Issue by hzhgino** [leaves615/KeyboardHolder#7]
1.虽然添加应用，不是经常需要做的操作，但是目前的添加方式，需要点击加号，在选择应用，才能进行添加。
建议产考「swtichkey」简化这个操作。
2.无法添加「聚焦搜索」进行锁定输入法
3.添加了应用之后，在选中这个应用， 右边选择输入法的select狂，会显示空白。

**Comment by leaves615** [comment]
1. 希望新版本能满足你的使用需求。
2. 【聚焦搜索】为系统App，暂时无法处理。
3. 请更新新版本。
