### ISSUE TITLE
1.61版本以上的点设置均闪退

### ISSUE THREAD

**Issue by ebasegykj** [leaves615/KeyboardHolder#71]
1.6.1版本正常可点开设置. 1.8系列点设置均闪退,
系统10.15

**Comment by leaves615** [comment]
感谢反馈，目前手头上没有能运行10.15系统的设备，无法调试情况。后续将在合适的时候修复10.15上面的问题。

**Comment by kefengzhang** [comment]
我这边也是有这样的问题,我只好回滚到1.6.1了

**Comment by gagadacry** [comment]
我是1.6.2正常，以上设置闪退，10.15.7
