### ISSUE TITLE
应用启动时与激活时的输入法切换冲突

### ISSUE THREAD

**Issue by k23450987** [leaves615/KeyboardHolder#72]
- 问题描述：
应用激活时的输入法与激活时的输入法切换冲突。设置为启动时使用英文输入法，激活后使用上次使用的输入法。但是启动应用后再次切换窗口，会激活为应用上次退出时使用的输入法。
<img width="912" alt="image" src="https://user-images.githubusercontent.com/3955621/176985388-f44ed35f-7c52-4965-97af-d5967df5b4b7.png">

- 应用版本：1.8.2

- 操作系统版本：12.4

- 问题可复现的操作步骤
  1. 设置启动时输入法为英文，激活时输入法为上次使用。
  2. 打开xmind，首次打开为ABC，切换成拼音，并且退出。
  3. 再次打开xmind，打开后输入法切换为ABC。
  4. 从xmind切出，再切换回xmind，上次使用的ABC没有被保留，输入法被切换到拼音。

- 问题时段和日志文件（可在 /Users/<username>/Library/Logs/KeyboardHolder 中找到）：[log.log](https://github.com/leaves615/KeyboardHolder/files/9032365/log.log)
- 是否启用了辅助控制：是

**Comment by k23450987** [comment]
备注：xmind没有被添加到自定义规则中，使用的是通用配置中的规则。

**Comment by leaves615** [comment]
感谢反馈。下个版本修复改问题。
