### ISSUE TITLE
建议：检测到当前光标是可输入状态时，自动弹出输入法提示

### ISSUE THREAD

**Issue by qq420100523** [leaves615/KeyboardHolder#74]
场景：长时间浏览帖子，可能会忘记当前的输入法状态，此时移动光标到回复框，正准备输入中文回复，才发现是英文输入法状态，输入了一些英文字符，还要回退删除，再切换到中文输入法。
功能：若是在移动光标到文字输入框时，便自动弹出输入法提示，根据提示来决定是否要切换输入法，则可以避免等到输入错误，才发现输入法状态，也省去回退删除操作。

**Comment by leaves615** [comment]
非常好的建议。

**Comment by lethefrost** [comment]
我也想要这个功能，希望每次从非输入状态切换到输入状态，开始输入之前，可不可以在**文本光标**附近（而不是鼠标指针附近）显示一下输入法呢？因为有些时候是通过快捷键调起的popup窗口，直接开始输入（而不需要鼠标移动到输入框、点击之后再输入），此时鼠标还在其他位置，但目光却是跟着弹出的输入框的，如果显示的输入法状态能跟随文本光标就好了。 @leaves615

**Comment by raymond8825** [comment]
这是一个不错的建议,期待中

**Comment by leaves615** [comment]
@lethefrost  跟随光标位置提示输入法状态，目前是没能力做到。没找到获取光标坐标位置的api。

**Comment by leaves615** [comment]
@KevinXC5  我用了下，很喜欢它可以跟踪光标。 但是能力不行，没有找到实现方法。

如果有知道方案的，感谢分享。

**Comment by leaves615** [comment]
@KevinXC5 大量搜索了stackoverflow 的帖子。找到个据说不是很完美的方法。能够拿到支持负责控制的app的文本光标。后续做个效果出来。

**Comment by lethefrost** [comment]
> @KevinXC5 大量搜索了stackoverflow 的帖子。找到个据说不是很完美的方法。能够拿到支持负责控制的app的文本光标。后续做个效果出来。

太太太感谢了，这两个功能真的会非常实用……流泪叩谢 您辛苦了！！

**Comment by KevinXC5** [comment]
> 法

大佬牛逼，期待后续版本👍

**Comment by leaves615** [comment]
跟随文本光标提示，很早之前也有想到过。当时没有搜索到方案，但是也没有看到除输入法以为其他应用有类似的功能应用，后面就放弃了。
