### ISSUE TITLE
[建议]切换中英文状态/不同窗口的时候浮动的状态栏能否跟随输入提示符而不是鼠标？

### ISSUE THREAD

**Issue by Sagasu777** [leaves615/KeyboardHolder#76]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/109566617/179651364-87309027-db12-47bb-8f54-d89b1ecb86b7.png">
如图所示，如果跟随输入提示符就会更加聚焦我要输入的地方，而不是鼠标在哪里就显示在哪里。
个人理解鼠标指针可能随机在任何地方（对于习惯用快捷键的我来说），但是输入提示符都是在固定位置。当我需要输入的时候能够清晰准确的告诉我当前是什么输入法以及是什么状态就是最棒了的。

BTW，软件做的很好，加油。

**Comment by leaves615** [comment]
之前有网友提个这个方案，目前没有找到可获取光标位置的方法。

**Comment by Sagasu777** [comment]
> 
是指在Macos中权限限制导致没有办法获取光标位置？
如果是这样的确实很难搞。不过目前已经很方便了。
顺便额外请教一下：
是否有遇到过实际上按了「中/英」键切换输入法，但是实际上就是没有反应，要多按几次才行的情况。我担心自己是个例现象。

**Comment by leaves615** [comment]
未找到 macOS 有提供相关api

中/英键切换没遇到过。

**Comment by KevinXC5** [comment]
input source pro有这个题主说的这个功能，不过不是开源软件，现在是免费的

**Comment by leaves615** [comment]
> input source pro有这个题主说的这个功能，不过不是开源软件，现在是免费的

在哪里配置。我怎么没有看到。

**Comment by KevinXC5** [comment]
> > input source pro有这个题主说的这个功能，不过不是开源软件，现在是免费的
> 
> 在哪里配置。我怎么没有看到。

<img width="710" alt="image" src="https://user-images.githubusercontent.com/27657061/182123297-fe7173d5-bd31-4a4c-b0e8-549d3bf3617b.png">
勾选这个设置，然后切换提示选择跟随光标就行了

**Comment by KevinXC5** [comment]
作者可以再研究下，应该是有方案可以实现的，我就是因为这个功能现在暂时从keyboardholder切换到input source pro了😂

**Comment by leaves615** [comment]
感谢分享
