### ISSUE TITLE
多屏下当前输入法提示位置不准

### ISSUE THREAD

**Issue by cooper-lyt** [leaves615/KeyboardHolder#77]
问题描述：
      当使用多个显示器并开启当前输入法提示功能，无论是在鼠标位置提示还是在屏幕位置提示，提示出现的位置都不对，大概是副屏的提示总是出现在主屏的右下角。
应用版本：
1.8.3
操作系统版本:
Mac mini M1
macOS Monterey 12.4

辅助控制已开启

**Comment by leaves615** [comment]
待我接多个屏幕试试。

**Comment by tianshuang** [comment]
单屏也有这个问题，我左下角和下侧同时闪提示

**Comment by leaves615** [comment]
单屏没遇到过你说的问题。可以重启应用再看看。
