### ISSUE TITLE
切换为搜狗之后，会自动切回ABC

### ISSUE THREAD

**Issue by eryajf** [leaves615/KeyboardHolder#79]
自动切回默认并不合适，比如我设置iterm默认为ABC，此时打算输入一些中文，将输入法切成搜狗，拼音打出来之后，等一会儿会自动切到ABC:

![Jul-28-2022 22-10-36](https://user-images.githubusercontent.com/33259379/181527233-190b5f47-e95d-40ee-8e65-2ec0686529e7.gif)

**Comment by leaves615** [comment]
app激活状态下， KeyboardHolder不会进行切换。 除非有其他窗口激活了。

**Comment by eryajf** [comment]
我大概知道原因了，iterm配置了一分钟自动刷新，然后激活配置的固定ABC，就变了，现在改成上次使用的输入法就好了

**Comment by eryajf** [comment]
目前在我这里这个问题仍然存在，而且非常烦人，几乎影响到日常工作没法正常推进。

一个建议：希望能出一个白名单，然后添加对应应用，在这个应用窗口下，不做任何处理，这样对我这种情况，会好很多！

**Comment by leaves615** [comment]
关闭搜狗的中英文切换，就可以了。

**Comment by eryajf** [comment]
这应该不是搜狗输入法的问题，感觉上像是终端的问题（因为这个情况只出现终端这一个场景，而其他地方切到中文输入的时候，都是没有这个问题的），只是目前我无法准确定位到根因。

**Comment by eryajf** [comment]
而且刚刚又验证了下，单纯在iterm终端切到中文输入，也不会有问题，只在vscode中打开的终端，会有这个问题
