### ISSUE TITLE
1.3版本UI问题

### ISSUE THREAD

**Issue by HaoshuaiXu** [leaves615/KeyboardHolder#8]
选中的条目，输入法选项那里会变成空白
![Xnip 2021-03-09  -  09-48-12  - @2x](https://user-images.githubusercontent.com/39985040/110406139-b55e5f80-80bc-11eb-8817-7858e605b35c.jpg)

**Comment by leaves615** [comment]
感谢反馈。 
请问系统版本是多少？

**Comment by HaoshuaiXu** [comment]
10.15.7

**Comment by leaves615** [comment]
该问题是swiftui 在10.15 才有，11 上面不存在。

**Comment by HaoshuaiXu** [comment]
Get，只能等待Swift自己修复了吗？

**Comment by leaves615** [comment]
> Get，只能等待Swift自己修复了吗？

10.11 已修复该问题。
