### ISSUE TITLE
设置隐藏图标后在忘记快捷键的情况下就无法打开主界面了

### ISSUE THREAD

**Issue by tianshuang** [leaves615/KeyboardHolder#81]
除非杀掉进程重新打开，能否像其他 app 一样隐藏后也能通过 app 图标打开应用

**Comment by tianshuang** [comment]
还有一个建议，首次安装配置了辅助功能后如果没有重启应用好像设置不会生效，只有重启了应用才生效

**Comment by leaves615** [comment]
快捷键冲突了吧？

**Comment by tianshuang** [comment]
不是，我的意思是忘记快捷键的情况下无法通过 app 图标打开主界面





------------------ 原始邮件 ------------------
发件人: leaves chen ***@***.***&gt;
发送时间: 2022年7月31日 12:56
收件人: leaves615/KeyboardHolder ***@***.***&gt;
抄送: Poison ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [leaves615/KeyboardHolder] 设置隐藏图标后在忘记快捷键的情况下就无法打开主界面了 (Issue #81)





 
快捷键冲突了吧？

**Comment by leaves615** [comment]
> 不是，我的意思是忘记快捷键的情况下无法通过 app 图标打开主界面
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: leaves chen ***@***.***&gt; 发送时间: 2022年7月31日 12:56 收件人: leaves615/KeyboardHolder ***@***.***&gt; 抄送: Poison ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [leaves615/KeyboardHolder] 设置隐藏图标后在忘记快捷键的情况下就无法打开主界面了 (Issue #81) 快捷键冲突了吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

目前只能通过状态栏图标进入。

**Comment by tianshuang** [comment]
嗯，因为状态栏图标也能隐藏，所以忘了快捷键的情况下就没有入口了，其他 app 可以通过图标重新打开。





------------------ 原始邮件 ------------------
发件人: leaves chen ***@***.***&gt;
发送时间: 2022年7月31日 13:04
收件人: leaves615/KeyboardHolder ***@***.***&gt;
抄送: Poison ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [leaves615/KeyboardHolder] 设置隐藏图标后在忘记快捷键的情况下就无法打开主界面了 (Issue #81)





  
不是，我的意思是忘记快捷键的情况下无法通过 app 图标打开主界面
 …
 ------------------ 原始邮件 ------------------ 发件人: leaves chen @.&gt; 发送时间: 2022年7月31日 12:56 收件人: leaves615/KeyboardHolder @.&gt; 抄送: Poison @.&gt;, Author @.&gt; 主题: Re: [leaves615/KeyboardHolder] 设置隐藏图标后在忘记快捷键的情况下就无法打开主界面了 (Issue #81) 快捷键冲突了吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
目前只能通过状态栏图标进入。

**Comment by leaves615** [comment]
@tianshuang  将在下个版本更新增加通过app再次启动来显示隐藏的状态栏图标。

**Comment by Lxuty** [comment]
快捷键是啥来着，忘记了～

**Comment by tianshuang** [comment]
> 快捷键是啥来着，忘记了～

<img width="173" alt="image" src="https://user-images.githubusercontent.com/10725601/182581529-c95c27bf-680d-4893-bd12-ec5ead63b175.png">
