### ISSUE TITLE
刚更新了新版本，切换输入发提示有bug

### ISSUE THREAD

**Issue by mycherish** [leaves615/KeyboardHolder#83]
问题描述：切换中英文输入法时，只显示一个小的灰色框
应用版本：1.9.0
操作系统版本：12.4
问题可复现的操作步骤：切换中英文输入法
![image](https://user-images.githubusercontent.com/37433102/182758610-c03c5053-fe57-4a82-b50f-9cd1721f58c2.png)

**Comment by leaves615** [comment]
尝试重新配置输入法提示显示效果。

**Comment by mycherish** [comment]
> 尝试重新配置输入法提示显示效果。

嗯嗯好了，重新选择了一下就好了

**Comment by qfdk** [comment]
是的，还出现切换提示为空的情况。
MacBook Pro M1 Pro 机器。解决方案重新配置，添加以下选项
<img width="641" alt="image" src="https://user-images.githubusercontent.com/2404478/182777039-64b4fb40-8520-448b-b275-b5e7ccf4382a.png">

**Comment by leaves615** [comment]
#84

**Comment by mycherish** [comment]
> #84

左右滑动切换桌面会在跳转到的桌面显示输入法提示，但是用commend+tab键切换桌面，只在前一个桌面显示输入法提示，切换后的桌面不显示
