### ISSUE TITLE
提示貌似有bug，输入框没选中时，也会提示，即便输入法并没有发生切换

### ISSUE THREAD

**Issue by winterant** [leaves615/KeyboardHolder#86]
为了更精准分析您遇到的问题。在填写时候请提供一下信息：

问题描述
1. 以微信和浏览器为例，两者都适用中文输入，两者之间的窗口在切换时，如果开了“输入法切换提示”，就会提示输入法，而实际上输入法一直保持中文没变，没必要提示
2. 仍以微信和浏览器为例，浏览器网页中并没有输入框，而从微信切换到浏览器时，也会提示输入法。这个也是没有必要的，因为页面上连输入框都没有。

建议：输入法的提示动作应当发生在输入框被点击为输入状态时，再提示输入法，而不是

应用版本
v1.9.0

操作系统版本
macOS 12.5

问题可复现的操作步骤
开启“输入法切换提示”

是否启用了辅助控制
是

**Comment by winterant** [comment]
补充：例如访达，打开访达时，没有任何输入框，也会提示输入法。其实完全可以等搜索框被点出来时，再提示输入法。

非常感谢作者开发的特别实用的软件！！！

**Comment by leaves615** [comment]
新版本已添加相关配置。
