### ISSUE TITLE
MacBook Pro（m1）睡眠再唤醒，偶尔出现自动退出

### ISSUE THREAD

**Issue by davidwudv** [leaves615/KeyboardHolder#88]
## 问题描述
每天晚上下班合上笔记本，早上再打开就发现KeyboardHolder就已经自动退出了，出现过很多次。

## 系统版本
macOS 12.5
MacBook Pro m1

## 应用版本
1.9.0～1.9.2 都出现过

## 日志
查了日志路径，没有任何崩溃日志。BTW，查日志的时候正好发现日志打印的时区不对- -

**Comment by leaves615** [comment]
看看控制台的奔溃日志。
<img width="314" alt="image" src="https://user-images.githubusercontent.com/375323/184060318-4a13020c-0306-4a0c-9c9d-e00274eddc1d.png">

**Comment by davidwudv** [comment]
> 看看控制台的奔溃日志。 <img alt="image" width="314" src="https://user-images.githubusercontent.com/375323/184060318-4a13020c-0306-4a0c-9c9d-e00274eddc1d.png">

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               KeyboardHolder [64079]
Path:                  /Applications/KeyboardHolder.app/Contents/MacOS/KeyboardHolder
Identifier:            cn.leaves.KeyboardHolder
Version:               1.9.1 (50)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-08-10 16:09:17.5626 +0800
OS Version:            macOS 12.5 (21G72)
Report Version:        12
Anonymous UUID:        EE5C8FEE-BE91-A49E-02E2-270F0C21D7E7

Sleep/Wake UUID:       EA058EF6-789C-4486-A1AE-8696AD650687

Time Awake Since Boot: 240000 seconds
Time Since Wake:       7427 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010404615c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [64079]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   KeyboardHolder                	       0x10404615c 0x104010000 + 221532
1   KeyboardHolder                	       0x104045994 0x104010000 + 219540
2   KeyboardHolder                	       0x1040578b0 0x104010000 + 293040
3   libdispatch.dylib             	       0x19f45c1b4 _dispatch_client_callout + 20
4   libdispatch.dylib             	       0x19f45f670 _dispatch_continuation_pop + 500
5   libdispatch.dylib             	       0x19f4728e0 _dispatch_source_invoke + 1596
6   libdispatch.dylib             	       0x19f46a620 _dispatch_main_queue_drain + 756
7   libdispatch.dylib             	       0x19f46a31c _dispatch_main_queue_callback_4CF + 44
8   CoreFoundation                	       0x19f72ea2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
9   CoreFoundation                	       0x19f6ebcb8 __CFRunLoopRun + 2532
10  CoreFoundation                	       0x19f6eab34 CFRunLoopRunSpecific + 600
11  HIToolbox                     	       0x1a832a338 RunCurrentEventLoopInMode + 292
12  HIToolbox                     	       0x1a832a0b4 ReceiveNextEventCommon + 564
13  HIToolbox                     	       0x1a8329e68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
14  AppKit                        	       0x1a225251c _DPSNextEvent + 860
15  AppKit                        	       0x1a2250e14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
16  AppKit                        	       0x1a2242fe0 -[NSApplication run] + 596
17  AppKit                        	       0x1a22146fc NSApplicationMain + 1132
18  KeyboardHolder                	       0x104015904 0x104010000 + 22788
19  dyld                          	       0x10433d08c start + 520

Thread 1:
0   libsystem_kernel.dylib        	       0x19f5e606c __semwait_signal + 8
1   libsystem_c.dylib             	       0x19f4eefc8 nanosleep + 220
2   libsystem_c.dylib             	       0x19f4f9b78 sleep + 52
3   KeyboardHolder                	       0x104116340 0x104010000 + 1073984
4   libsystem_pthread.dylib       	       0x19f62026c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x19f61b08c thread_start + 8

Thread 2:: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib        	       0x19f5e28b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x19f5e2d20 mach_msg + 76
2   KeyboardHolder                	       0x104111d04 0x104010000 + 1056004
3   libsystem_pthread.dylib       	       0x19f62026c _pthread_start + 148
4   libsystem_pthread.dylib       	       0x19f61b08c thread_start + 8

Thread 3:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	       0x19f5e28b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x19f5e2d20 mach_msg + 76
2   CoreFoundation                	       0x19f6ed2c0 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x19f6eb770 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x19f6eab34 CFRunLoopRunSpecific + 600
5   CFNetwork                     	       0x1a44e2638 0x1a4277000 + 2537016
6   Foundation                    	       0x1a05c860c __NSThread__start__ + 808
7   libsystem_pthread.dylib       	       0x19f62026c _pthread_start + 148
8   libsystem_pthread.dylib       	       0x19f61b08c thread_start + 8

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19f5e28b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x19f5e2d20 mach_msg + 76
2   CoreFoundation                	       0x19f6ed2c0 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x19f6eb770 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x19f6eab34 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1a23bf100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x19f62026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x19f61b08c thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x19f61b078 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x19f61b078 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x19f61b078 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000016bdedeb0   x1: 0x0000000000000001   x2: 0x00000001f8e12618   x3: 0x1000000000000000
    x4: 0x1000000000000000   x5: 0x0000000000000063   x6: 0x0000000000000000   x7: 0x00006000019b4410
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0xfffffffe00000000  x11: 0x77df894aabe2642a
   x12: 0x80000002ffffffff  x13: 0x0800000000000000  x14: 0x0000000104139940  x15: 0xb7050bd588e87469
   x16: 0x00000001f8e125e8  x17: 0x60f00001f8e125e8  x18: 0x0000000000000000  x19: 0x000000016bdedf00
   x20: 0x00000001f863f100  x21: 0x00000001041d22f0  x22: 0x4000600002ce4840  x23: 0x00006000022f1cd0
   x24: 0x0000000000000001  x25: 0x000000012c70ca40  x26: 0x0000600002ce4840  x27: 0x0000600000ca3b80
   x28: 0x00006000022f1d00   fp: 0x000000016bdee0b0   lr: 0x0000000104045994
    sp: 0x000000016bdedef0   pc: 0x000000010404615c cpsr: 0x60001000
   far: 0x00000001f856cff8  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x104010000 -        0x104187fff cn.leaves.KeyboardHolder (1.9.1) <45d268b7-fa2d-366d-ae68-c87066b0f9eb> /Applications/KeyboardHolder.app/Contents/MacOS/KeyboardHolder
       0x19f458000 -        0x19f49efff libdispatch.dylib (*) <035d23d9-4cb5-3759-9059-1f7878f89fee> /usr/lib/system/libdispatch.dylib
       0x19f668000 -        0x19fbaefff com.apple.CoreFoundation (6.9) <1643f3d9-7049-37e4-b844-c0c0a42bde3b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a82f8000 -        0x1a862bfff com.apple.HIToolbox (2.1.1) <7112f6f2-a77e-39db-83c8-f627b8a49df8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1a2211000 -        0x1a30c9fff com.apple.AppKit (6.9) <07bc3607-552a-3eb9-a941-4911c589dbc5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x104338000 -        0x104397fff dyld (*) <75627683-a780-32ad-ae34-cf86dd23a26b> /usr/lib/dyld
       0x19f5e1000 -        0x19f618fff libsystem_kernel.dylib (*) <67f22904-88ed-3847-bbf0-5c4c599fd79e> /usr/lib/system/libsystem_kernel.dylib
       0x19f4e0000 -        0x19f561fff libsystem_c.dylib (*) <93fc2587-038e-31e1-b16b-369979e72cb1> /usr/lib/system/libsystem_c.dylib
       0x19f619000 -        0x19f625fff libsystem_pthread.dylib (*) <f32ff902-ba43-30b0-ad43-a2a8a9ff69fe> /usr/lib/system/libsystem_pthread.dylib
       0x1a4277000 -        0x1a472bfff com.apple.CFNetwork (1335.0.3) <f0720ccf-fe46-3541-8835-dbaa254cef61> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
       0x1a056c000 -        0x1a095dfff com.apple.Foundation (6.9) <59ff845a-05b2-3b64-ae06-6ef1d6aee83e> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 117
    thread_create: 0
    thread_set_state: 1614

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
ColorSync                          544K       24 
CoreAnimation                       16K        1 
CoreGraphics                        32K        2 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           275.7M       68 
MALLOC guard page                  288K       15 
MALLOC_MEDIUM (reserved)         840.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  256K        4 
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                         80K        5 
__AUTH                            2443K      254 
__AUTH_CONST                      19.0M      441 
__CTF                               756        1 
__DATA                            12.3M      430 
__DATA_CONST                      15.7M      447 
__DATA_DIRTY                      1555K      170 
__FONT_DATA                          4K        1 
__LINKEDIT                       578.0M        5 
__OBJC_CONST                      2634K      213 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           453.1M      464 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                         128K        8 
mapped file                      148.0M       25 
shared memory                      848K       12 
===========                     =======  ======= 
TOTAL                              2.8G     2623 
TOTAL, minus reserved VM space     1.6G     2623 



-----------
Full Report
-----------

{"app_name":"KeyboardHolder","timestamp":"2022-08-10 16:09:20.00 +0800","app_version":"1.9.1","slice_uuid":"45d268b7-fa2d-366d-ae68-c87066b0f9eb","build_version":"50","platform":1,"bundleID":"cn.leaves.KeyboardHolder","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5 (21G72)","incident_id":"20A51E10-40F2-4303-B635-BEE1B73D0806","name":"KeyboardHolder"}
{
  "uptime" : 240000,
  "procLaunch" : "2022-08-10 10:57:12.1948 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 5689108312597,
  "coalitionID" : 32703,
  "osVersion" : {
    "train" : "macOS 12.5",
    "build" : "21G72",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-10 16:09:17.5626 +0800",
  "incident" : "20A51E10-40F2-4303-B635-BEE1B73D0806",
  "bug_type" : "309",
  "pid" : 64079,
  "procExitAbsTime" : 5962061042970,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "KeyboardHolder",
  "procPath" : "\/Applications\/KeyboardHolder.app\/Contents\/MacOS\/KeyboardHolder",
  "bundleInfo" : {"CFBundleShortVersionString":"1.9.1","CFBundleVersion":"50","CFBundleIdentifier":"cn.leaves.KeyboardHolder"},
  "storeInfo" : {"deviceIdentifierForVendor":"40E49224-F605-56AD-A80A-582643F411FE","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "cn.leaves.KeyboardHolder",
  "crashReporterKey" : "EE5C8FEE-BE91-A49E-02E2-270F0C21D7E7",
  "wakeTime" : 7427,
  "sleepWakeUUID" : "EA058EF6-789C-4486-A1AE-8696AD650687",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x000000010404615c","rawCodes":[1,4362363228],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":64079},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":1614,"task_for_pid":117},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2946967,"threadState":{"x":[{"value":6104735408},{"value":1},{"value":8470472216,"symbolLocation":8,"symbol":"type metadata for Any"},{"value":1152921504606846976},{"value":1152921504606846976},{"value":99},{"value":0},{"value":105553143219216},{"value":0},{"value":0},{"value":18446744065119617024},{"value":8637773564124226602},{"value":9223372049739677695},{"value":576460752303423488},{"value":4363360576},{"value":13187960095577240681},{"value":8470472168,"symbolLocation":48,"symbol":"OpaqueExistentialValueWitnesses_0"},{"value":6985083030522111464},{"value":0},{"value":6104735488},{"value":8462266624,"symbolLocation":0,"symbol":"_swiftEmptyDictionarySingleton"},{"value":4363985648},{"value":4611791571590727744},{"value":105553152908496},{"value":1},{"value":5040556608},{"value":105553163339840},{"value":105553129520000},{"value":105553152908544}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4362361236},"cpsr":{"value":1610616832},"fp":{"value":6104735920},"sp":{"value":6104735472},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4362363228,"matchesCrashFrame":1},"far":{"value":8461406200}},"queue":"com.apple.main-thread","frames":[{"imageOffset":221532,"imageIndex":0},{"imageOffset":219540,"imageIndex":0},{"imageOffset":293040,"imageIndex":0},{"imageOffset":16820,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":30320,"symbol":"_dispatch_continuation_pop","symbolLocation":500,"imageIndex":1},{"imageOffset":108768,"symbol":"_dispatch_source_invoke","symbolLocation":1596,"imageIndex":1},{"imageOffset":75296,"symbol":"_dispatch_main_queue_drain","symbolLocation":756,"imageIndex":1},{"imageOffset":74524,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":44,"imageIndex":1},{"imageOffset":813612,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":539832,"symbol":"__CFRunLoopRun","symbolLocation":2532,"imageIndex":2},{"imageOffset":535348,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":205624,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":204980,"symbol":"ReceiveNextEventCommon","symbolLocation":564,"imageIndex":3},{"imageOffset":204392,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":3},{"imageOffset":267548,"symbol":"_DPSNextEvent","symbolLocation":860,"imageIndex":4},{"imageOffset":261652,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1328,"imageIndex":4},{"imageOffset":204768,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":4},{"imageOffset":14076,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":4},{"imageOffset":22788,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":5}]},{"id":2947000,"frames":[{"imageOffset":20588,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":6},{"imageOffset":61384,"symbol":"nanosleep","symbolLocation":220,"imageIndex":7},{"imageOffset":105336,"symbol":"sleep","symbolLocation":52,"imageIndex":7},{"imageOffset":1073984,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":2947001,"name":"SentryCrash Exception Handler (Secondary)","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":1056004,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":2947016,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":545472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":538480,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":2},{"imageOffset":535348,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":2537016,"imageIndex":9},{"imageOffset":378380,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":10},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":2947022,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":545472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":538480,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":2},{"imageOffset":535348,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1761536,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":4},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":3086208,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":3087105,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":3087106,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4362141696,
    "CFBundleShortVersionString" : "1.9.1",
    "CFBundleIdentifier" : "cn.leaves.KeyboardHolder",
    "size" : 1540096,
    "uuid" : "45d268b7-fa2d-366d-ae68-c87066b0f9eb",
    "path" : "\/Applications\/KeyboardHolder.app\/Contents\/MacOS\/KeyboardHolder",
    "name" : "KeyboardHolder",
    "CFBundleVersion" : "50"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6967099392,
    "size" : 290816,
    "uuid" : "035d23d9-4cb5-3759-9059-1f7878f89fee",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6969262080,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "1643f3d9-7049-37e4-b844-c0c0a42bde3b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7116652544,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "7112f6f2-a77e-39db-83c8-f627b8a49df8",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7015043072,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "07bc3607-552a-3eb9-a941-4911c589dbc5",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4365451264,
    "size" : 393216,
    "uuid" : "75627683-a780-32ad-ae34-cf86dd23a26b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6968709120,
    "size" : 229376,
    "uuid" : "67f22904-88ed-3847-bbf0-5c4c599fd79e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6967656448,
    "size" : 532480,
    "uuid" : "93fc2587-038e-31e1-b16b-369979e72cb1",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6968938496,
    "size" : 53248,
    "uuid" : "f32ff902-ba43-30b0-ad43-a2a8a9ff69fe",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7049015296,
    "CFBundleShortVersionString" : "1335.0.3",
    "CFBundleIdentifier" : "com.apple.CFNetwork",
    "size" : 4935680,
    "uuid" : "f0720ccf-fe46-3541-8835-dbaa254cef61",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/Versions\/A\/CFNetwork",
    "name" : "CFNetwork",
    "CFBundleVersion" : "1335.0.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6985007104,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4136960,
    "uuid" : "59ff845a-05b2-3b64-ae06-6ef1d6aee83e",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1866"
  }
],
  "sharedCache" : {
  "base" : 6965641216,
  "size" : 3144695808,
  "uuid" : "ffede77c-d90b-366b-96f2-665c2f50ee59"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nColorSync                          544K       24 \nCoreAnimation                       16K        1 \nCoreGraphics                        32K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           275.7M       68 \nMALLOC guard page                  288K       15 \nMALLOC_MEDIUM (reserved)         840.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  256K        4 \nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                         80K        5 \n__AUTH                            2443K      254 \n__AUTH_CONST                      19.0M      441 \n__CTF                               756        1 \n__DATA                            12.3M      430 \n__DATA_CONST                      15.7M      447 \n__DATA_DIRTY                      1555K      170 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       578.0M        5 \n__OBJC_CONST                      2634K      213 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           453.1M      464 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      148.0M       25 \nshared memory                      848K       12 \n===========                     =======  ======= \nTOTAL                              2.8G     2623 \nTOTAL, minus reserved VM space     1.6G     2623 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "628bd2fda5168570b594bb52"
      },
      "deploymentId" : 240000137
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by leaves615** [comment]
新版本应该是解决了问题点。这个还待进一步监控。我本机从来没遇到过这种情况。
