### ISSUE TITLE
输入法提示与dock栏重叠

### ISSUE THREAD

**Issue by cenlibin** [leaves615/KeyboardHolder#89]
输入法提示悬浮窗设置位置为屏幕中下的时候与dock栏重叠很难受，是不是可以再往上一点，或者可以给用户修改配置文件挪位置？

<img width="518" alt="image" src="https://user-images.githubusercontent.com/44693016/184548705-be294f4b-0d4f-4d34-b42b-5c4b74d8d9c3.png">

**Comment by leaves615** [comment]
新版本已修复。
