### ISSUE TITLE
与VS Code冲突

### ISSUE THREAD

**Issue by dufu1991** [leaves615/KeyboardHolder#90]
1.9.3（53）版本发现一个奇怪的问题。
在VS Code里面选定一段文字之后，切换应用回来之后，KeyboardHolder切换输入法的时候会将刚刚选定的文字剪切！！
还以为是VS Code的问题，试了各种方法，发现退出KeyboardHolder就正常了。

**Comment by leaves615** [comment]
可以禁用优先在文本光标位置显示。来避免这个问题。 感谢您的反馈。

**Comment by leaves615** [comment]
新版已修正删除选中文本的问题。

**Comment by winterant** [comment]
最新版v1.9.4貌似有个bug，全程没有按过中英切换键，但是输入法却在不停切换。
以终端.app 和 备忘录.app为例，全程没有按过任何按键，但是中英文切换。
https://user-images.githubusercontent.com/37205944/185934828-4117b6d4-c92e-4bac-ac47-2a298d2c858b.mp4

**Comment by leaves615** [comment]
> 最新版v1.9.4貌似有个bug，全程没有按过中英切换键，但是输入法却在不停切换。 以终端.app 和 备忘录.app为例，全程没有按过任何按键，但是中英文切换了。 https://user-images.githubusercontent.com/37205944/185934828-4117b6d4-c92e-4bac-ac47-2a298d2c858b.mp4

已知bug，请更新最新版本
