### ISSUE TITLE
v1.9.4 bug：中英文会自动切换，没法保持离开时的输入法

### ISSUE THREAD

**Issue by winterant** [leaves615/KeyboardHolder#92]
问题描述
最新版v1.9.4貌似有个bug，全程没有按过中英切换键，但是输入法却在不停切换。
以终端.app 和 备忘录.app为例，全程没有按过任何按键，但是中英文切换了。
https://user-images.githubusercontent.com/37205944/185934828-4117b6d4-c92e-4bac-ac47-2a298d2c858b.mp4

应用版本v1.9.4

操作系统版本 macos 12.5.1

问题可复现的操作步骤：任意两个app来回切换即可复现。

问题时段和日志文件（可在 /Users/<username>/Library/Logs/KeyboardHolder 中找到）
没有

是否启用了辅助控制：是

**Comment by leaves615** [comment]
已知bug，请更新最新版本
