### ISSUE TITLE
从ABC切换回搜狗输入法时，即使是搜狗的英文输入模式也变回中文输入模式

### ISSUE THREAD

**Issue by smilingpoplar** [leaves615/KeyboardHolder#94]
如 #69 说过，第三方没法管理搜狗输入法状态。退一步，让某些app自动切换英文。搜狗有自动切英文的app清单设置，但是功能失灵时不灵。

keyboardholder能不能在切换输入法时，自定义一个切换后调用的快捷键（比如搜狗切换中英文的shift键）？

**Comment by leaves615** [comment]
切换调用自定的快捷键是一个很好的临时解决方案。快捷键基于事件处理，它会出现不确定性的时延。从而让该功能出现很多的不确定性。

**Comment by smilingpoplar** [comment]
有道理
