### ISSUE TITLE
无法保存输入法状态

### ISSUE THREAD

**Issue by imbytecat** [leaves615/KeyboardHolder#95]
- 无法获取输入法状态，表现为没有切换输入法气泡提示（如在 Chrome 中），且不能记住输入法状态；定义了确切输入法的 App 是可以正常切换的，但是所有和记住输入法相关的设置都不起作用
- 软件版本1.10.0 (55)
- macOS 12.5.1 (21G83)
- 已经启用辅助控制
<img width="912" alt="image" src="https://user-images.githubusercontent.com/15844288/187088835-02595fd4-26fd-4686-9e7e-cec14e6012c3.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/15844288/187088851-2311eb16-3ae0-4c66-ad1c-ba999495def6.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/15844288/187088856-23778252-4bc3-4485-80d5-5ea2957dcb34.png">

**Comment by imbytecat** [comment]
重启后自行解决，似乎恢复了正常，估计是 macOS 的问题。

**Comment by leaves615** [comment]
尝试重新启动下Chrome

imbytecat ***@***.***> 于2022年8月29日周一 02:07写道：
