### ISSUE TITLE
最新版怎么浏览器地址不工作了

### ISSUE THREAD

**Issue by shruru** [leaves615/KeyboardHolder#96]
就完全不工作了, 无论设置了什么, 没有一个浏览器地址能匹配正确...
记得以前是好的. 

MacOSX 最新操作系统. Chrome 浏览器 最新版
另外选项里面这个 浏览器地址定制是什么意思? 和 域名那个标签页之间的关系是什么? 也是一头雾水.. 😂

<img width="407" alt="image" src="https://user-images.githubusercontent.com/2038477/193468352-3dfce5ce-8c74-49b5-bfef-7bdecb17c1b0.png">

...

**Comment by leaves615** [comment]
辅助控制有没有启用呢？

shruru ***@***.***> 于2022年10月3日周一 01:46写道：

**Comment by shruru** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/2038477/193488696-2ed56656-7814-42fc-9787-7dc400b229a8.png">
所有的设置都没动过. 前几个版本都是好的. 后来在线提示更新, 我没注意都点了更新, 现在这几天...发现它根本不工作了

**Comment by leaves615** [comment]
请#56反馈具体信息。
