### ISSUE TITLE
不同应用切换时，输入法乱了

### ISSUE THREAD

**Issue by mycherish** [leaves615/KeyboardHolder#97]
1. 两个应用，一个设置的是启动时abc，激活时上次使用的输入法，另一个应用，启动时简体拼音，激活时也是上次使用的输入法，但是应用切换时，这俩应用一会时abc一会是简体拼音，我找了一个规律就是，出现两次简体拼音，出现一次ABC，然后循环
2. 应用版本
![image](https://user-images.githubusercontent.com/37433102/195787679-e9177dc5-8fb3-4618-954a-14e4c238e041.png)
3. 操作系统版本：M1 的macOS Monterey 12.6

**Comment by mcwq123** [comment]
我也遇到了这个问题, 有时候切换会失败

**Comment by leaves615** [comment]
尝试删除/Application/Keyboardholder.app , 重新安装。

**Comment by leaves615** [comment]
#56  参照这个，提供下你的本地日志。谢谢。

**Comment by mycherish** [comment]
> #56 参照这个，提供下你的本地日志。谢谢。

2022/10/18 01:19:15:478  defaultLaunchId: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:15:478  defaultActiveId: Optional("last")
2022/10/18 01:19:15:478  cachedId: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:15:478  isCustom: false
2022/10/18 01:19:15:478  cached: true
2022/10/18 01:19:15:478  not custom
2022/10/18 01:19:15:478  active
2022/10/18 01:19:15:478  last
2022/10/18 01:19:15:478  target id: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:15:478  switching: Optional("ABC"), org.vim.MacVim
2022/10/18 01:19:15:478  switch input for nomal app.
2022/10/18 01:19:15:478  show tips
2022/10/18 01:19:15:508  cache status: org.vim.MacVim Optional(<TSMInputSource 0x6000009b6ee0> KB Layout: ABC (id=252))
2022/10/18 01:19:15:508  change: ABC for identifer: org.vim.MacVim
2022/10/18 01:19:15:508  start change.
2022/10/18 01:19:15:508  current input source is correct, no need to do nothing.
2022/10/18 01:19:16:000  applicationActivated on Optional("<AXApplication \"com.google.Chrome\" (pid=480)>"); pid:[480] info: [:] at com.google.Chrome
2022/10/18 01:19:16:004  browser domain get failed addrEle is: nil
2022/10/18 01:19:16:005  focus element: Optional(<AXTextArea "<AXUIElement 0x600000634660> {pid=480}" (pid=480)>)
2022/10/18 01:19:16:005  --- end for app[480] switch flag[0x00006000009873c0] is 10100001
2022/10/18 01:19:16:005  flag string: applicationActived isBrowserProcess textAreaActived 
2022/10/18 01:19:16:005  appInputStatus: ["notion.id": "com.apple.inputmethod.SCIM.ITABC", "com.postmanlabs.mac": "com.apple.keylayout.ABC", "com.tencent.Lemon": "com.apple.keylayout.ABC", "com.apple.finder": "com.apple.inputmethod.SCIM.ITABC", "com.apple.dt.Xcode": "com.apple.keylayout.ABC", "com.kinghow.mac": "com.apple.inputmethod.SCIM.ITABC", "org.vim.MacVim": "com.apple.keylayout.ABC", "com.googlecode.iterm2": "com.apple.inputmethod.SCIM.ITABC", "cn.leaves.KeyboardHolder": "com.apple.keylayout.ABC", "com.lowtechguys.rcmd": "com.apple.keylayout.ABC", "com.navicat.NavicatPremium": "com.apple.inputmethod.SCIM.ITABC", "com.google.Chrome": "com.apple.keylayout.ABC", "com.jetbrains.PhpStorm": "com.apple.keylayout.ABC", "com.apple.reminders": "com.apple.inputmethod.SCIM.ITABC", "com.torusknot.SourceTreeNotMAS": "com.apple.inputmethod.SCIM.ITABC", "com.robinlu.mac.Tooth-Fairy": "com.apple.keylayout.ABC", "5ZSL2CJU2T.com.dingtalk.mac": "com.apple.keylayout.ABC", "abnerworks.Typora": "com.apple.keylayout.ABC", "com.tencent.WeWorkMac": "com.apple.inputmethod.SCIM.ITABC", "com.apple.Notes": "com.apple.keylayout.ABC", "com.tencent.xinWeChat": "com.apple.keylayout.ABC"]
2022/10/18 01:19:16:005  bundleIdentifier: com.google.Chrome
2022/10/18 01:19:16:005  appLaunchId: nil
2022/10/18 01:19:16:005  appActiveId: nil
2022/10/18 01:19:16:005  defaultLaunchId: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:16:005  defaultActiveId: Optional("last")
2022/10/18 01:19:16:005  cachedId: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:16:005  isCustom: false
2022/10/18 01:19:16:005  cached: true
2022/10/18 01:19:16:005  not custom
2022/10/18 01:19:16:005  active
2022/10/18 01:19:16:005  last
2022/10/18 01:19:16:005  target id: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:28:662  applicationActivated on Optional("<AXApplication \"org.vim.MacVim\" (pid=54807)>"); pid:[54807] info: [:] at org.vim.MacVim
2022/10/18 01:19:28:662  focus element: Optional(<AXWindow "cn.leaves.KeyboardHolder 2022-10-17--09-36-35-206.log (~/Library/Logs/KeyboardHolder) - VIM" (pid=54807)>)
2022/10/18 01:19:28:662  --- end for app[54807] switch flag[0x00006000009ac240] is 1
2022/10/18 01:19:28:662  flag string: applicationActived 
2022/10/18 01:19:28:663  switch input for app org.vim.MacVim
2022/10/18 01:19:28:663  appInputStatus: ["notion.id": "com.apple.inputmethod.SCIM.ITABC", "com.postmanlabs.mac": "com.apple.keylayout.ABC", "com.tencent.Lemon": "com.apple.keylayout.ABC", "com.apple.finder": "com.apple.inputmethod.SCIM.ITABC", "com.apple.dt.Xcode": "com.apple.keylayout.ABC", "com.kinghow.mac": "com.apple.inputmethod.SCIM.ITABC", "org.vim.MacVim": "com.apple.keylayout.ABC", "com.googlecode.iterm2": "com.apple.inputmethod.SCIM.ITABC", "cn.leaves.KeyboardHolder": "com.apple.keylayout.ABC", "com.lowtechguys.rcmd": "com.apple.keylayout.ABC", "com.navicat.NavicatPremium": "com.apple.inputmethod.SCIM.ITABC", "com.google.Chrome": "com.apple.keylayout.ABC", "com.jetbrains.PhpStorm": "com.apple.keylayout.ABC", "com.apple.reminders": "com.apple.inputmethod.SCIM.ITABC", "com.torusknot.SourceTreeNotMAS": "com.apple.inputmethod.SCIM.ITABC", "com.robinlu.mac.Tooth-Fairy": "com.apple.keylayout.ABC", "5ZSL2CJU2T.com.dingtalk.mac": "com.apple.keylayout.ABC", "abnerworks.Typora": "com.apple.keylayout.ABC", "com.tencent.WeWorkMac": "com.apple.inputmethod.SCIM.ITABC", "com.apple.Notes": "com.apple.keylayout.ABC", "com.tencent.xinWeChat": "com.apple.keylayout.ABC"]
2022/10/18 01:19:28:663  bundleIdentifier: org.vim.MacVim
2022/10/18 01:19:28:663  appLaunchId: nil
2022/10/18 01:19:28:663  appActiveId: nil
2022/10/18 01:19:28:663  defaultLaunchId: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:28:663  defaultActiveId: Optional("last")
2022/10/18 01:19:28:663  cachedId: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:28:663  isCustom: false
2022/10/18 01:19:28:663  cached: true
2022/10/18 01:19:28:663  not custom
2022/10/18 01:19:28:663  active
2022/10/18 01:19:28:663  last
2022/10/18 01:19:28:663  target id: Optional("com.apple.keylayout.ABC")
2022/10/18 01:19:28:663  switching: Optional("ABC"), org.vim.MacVim
2022/10/18 01:19:28:663  switch input for nomal app.
2022/10/18 01:19:28:663  show tip

**Comment by leaves615** [comment]
这是出现问题时候的日志吗？

**Comment by leaves615** [comment]
没有哦，你发的日志看不出问题。
建议你复现场景，然后把日志文件发上来。

**Comment by mycherish** [comment]
> 没有哦，你发的日志看不出问题。 建议你复现场景，然后把日志文件发上来。

[cn.leaves.KeyboardHolder 2022-10-19--01-11-28-472.log](https://github.com/leaves615/KeyboardHolder/files/9816015/cn.leaves.KeyboardHolder.2022-10-19--01-11-28-472.log)

**Comment by leaves615** [comment]
日志看不出问题。 所有的切换都是正确的。 或许可以录个视频看看。

**Comment by mycherish** [comment]
https://user-images.githubusercontent.com/37433102/196853220-33f66732-a744-4b8e-9c95-156439cdc9d8.mov

**Comment by leaves615** [comment]
🤔，确实是这个问题。

**Comment by leaves615** [comment]
非常感谢您的耐心，以及提供复现的必要信息。

**Comment by mycherish** [comment]
一直在用，希望能尽快修复，之前版本没有发现过这个问题

**Comment by leaves615** [comment]
我在zoc 和微信两个app切换中复现了你所述的问题。但是发现zoc出现了非预期的自动切换（暂时没有找到源头）。在经过多次验证无果后，我关闭了Keyboardolder，再次在zoc（英文）和微信（拼音）之间切换仓库，发现zoc会自动切换到英文输入法。 而在Chrome和微信之间是不存在以上问题的。

@mycherish  再次麻烦你，在关闭Keyboardolder的情况下，尝试在有问题的两个app间进行不一致切换。

**Comment by mycherish** [comment]
> 我在zoc 和微信两个app切换中复现了你所述的问题。但是发现zoc出现了非预期的自动切换（暂时没有找到源头）。在经过多次验证无果后，我关闭了Keyboardolder，再次在zoc（英文）和微信（拼音）之间切换仓库，发现zoc会自动切换到英文输入法。 而在Chrome和微信之间是不存在以上问题的。
> 
> @mycherish 再次麻烦你，在关闭Keyboardolder的情况下，尝试在有问题的两个app间进行不一致切换。

我想我知道问题的所在了，我关闭了 Keyboardolder 也确实会有问题，我去掉勾选 自动切换到文稿输入法 就好了，不太清楚这个选项有什么作用，勾选了自动切换到文稿输入法，然后关闭 Keyboardolder，在微信也企业微信之间切换也有问题

**Comment by leaves615** [comment]
自动切换到文稿输入法 这个是macOS自带的文稿输入法切换功能。它能够记忆一定时间内的文稿切换，没有更多的控制。KeyboardHolder 是对它的扩展。

**Comment by mycherish** [comment]
> 自动切换到文稿输入法 这个是macOS自带的文稿输入法切换功能。它能够记忆一定时间内的文稿切换，没有更多的控制。KeyboardHolder 是对它的扩展。

那也就是它自带的是根据习惯去自动切换，不能自定义
