### ISSUE TITLE
无法配置 输入法快捷键

### ISSUE THREAD

**Issue by Valar103769** [leaves615/KeyboardHolder#98]
为了更精准分析您遇到的问题。在填写时候请提供一下信息：

这是输入框还是什么? 总之无法修改任何东西

另外如何配置, 中文下使用英文标点,mac自带的标点配置无效
<img width="836" alt="image" src="https://user-images.githubusercontent.com/36926073/204738049-91424ac7-fd62-4f3e-bc4b-a9eaca519513.png">

问题描述
应用版本 
操作系统版本

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 127.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.121
    Firefox Developer Edition: 105.0
    Safari: 15.6.1

问题可复现的操作步骤
问题时段和日志文件（可在 /Users/<username>/Library/Logs/KeyboardHolder 中找到）
https://jsbin.com/malatut/edit?html,js,output

是否启用了辅助控制:yes

**Comment by leaves615** [comment]
需要组合键配置。比如ctrl+e，你可以试试，单个键不能使用，容易冲突。

**Comment by Valar103769** [comment]
可我就是要覆盖默认的中英文切换键啊
